[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bdb8616d9be5625b0844bd8853c04c18fe82d721"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "4421eb515b42367d21df0e8ab333ebaedd58014159e4100e4eafe3dd838a3f57"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.i686-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07d21c828790d636b11f4d64d7e04132e76e7208"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "449d1e96e1ccb4ed26dd6cdd35ab856ea3804f6dbd21e0c978223e5b74d3cf15"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0866f798cf672bc4234e99ed950634acb78bd6ff"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "7d98b937154d6acadbad40054b111247e1fe96f4ae50f8cfd680e0573467fa48"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.i686-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3ec0aec4ce0cbefabaaa11c030fed25dccf8a91"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "13d6fb9e6d5bc4eb7c771b7f85a20a751cb24cbb6bc41ea09e8a5de41cf4c945"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "62d0079dc6e732706ac2f640adb344ee2a7ad316"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "4a1085c5751eaef786f84bbefb24b114b8426ce65360a155fff0eb379e8dded3"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "83ca1c9b14d9eb8464532191293d11294a94c6f4"
os = "macos"

    [[libLLVM.download]]
    sha256 = "562e658db274502c129bdc140df3ca170192dd8b9e92c442f1fd985799595c49"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e07a3733bab2667170ba8105da4ee2ea8617f420"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "9198463655c9c7a889e28fd15c0f413cad8c89c402be40415b3f8dce0da66816"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5550887957c5e3fbaab6758fe7719c1310bf9ead"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "db66e70dde612f787f50a463a38eaa3268275b2d8c072949ac7f45f5edc38ac2"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "964a30acc8225775a767dc6c0a3dcad82502d8bd"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "94c85a02f3afaedfc28441f0baefec6eaac8188c891ee9daf36db1b56cf32c9a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d97a4767a6fdcc18116f0e56ba63073eb06b690"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "61a241a1ec0c91bddfb2d01e37bfc23638af13b9dd1332eef5eaa3e35d58b004"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.arm-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f5b9d97ad66344b2fbf734cd6cb862112e0fd0a"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "3d604343a54b75f27d9427e00208a23911af1bb04dc37c1441ca8fdef5ba121f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "475580ad6617c00c19ba8cefaed76a70df51c3e7"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "30829387ad49bfa20f2e9ec8a1cf246c6b27a2a4f1a9da72bf92912e17c9ce01"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b0d0158dfb5b8fcc9bd4050103082cd878921115"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "3e8b1d712bd78be159336deffa4e5edabe6cca6b568c63d934a5e2c70cd0682c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.arm-linux-musleabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83ca1c9b14d9eb8464532191293d11294a94c6f4"
os = "macos"

    [[libLLVM.download]]
    sha256 = "e8afe00c8b2aa00f2c6c4d8c9a1968e7d0226962cdc778f32e1724a6522670de"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cee8bc8cba9dca1576f94f86730b4ebb6f5d3fdb"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "3ff9ec0c361cb6903023c2e039bf48edae7a2f98f6c4581bbdd10a1df79972b3"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e18c3ddeaae07b8669ef9764fb6560287ec8e987"
os = "windows"

    [[libLLVM.download]]
    sha256 = "1bfdc74c2b1a809b19a5c7cc361705155fdbc661897fd95faa64f259de93bbad"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4c6896af077ea012988c27772c0328c1171b7f4a"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "101e3d760e35509f4ef1832376b5e54e2c8e8f1f90511fbdf277615d39855382"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.arm-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48c79272db07213ddc90c026b3e028f0bade08f7"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "bdea5309c4bd7ce834202c943d9c9ffd6170fb874297ba589c471ed70bb334fa"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c2ef8c4fff7915953afef10cd7138f7b21e9ac6f"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "a9187407a115f95c5cc5e4b6cea0370651458457671505d938144fec572fb595"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd67de33c844bdf0b51f49998ca38c672763f578"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "c2277a3c4857de000cf8d2ef3fec004cb0133578caf378bbb6f362425499a052"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.arm-linux-musleabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f25025029ad7a1d9db8618b27cfa71e96b3e8962"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "80e3b484ee22b366e23a284f7624c9c55f802d078c1ab7f2769ed042999667eb"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd11a0506d6042c0c7f357fe32b74a849a529cf5"
os = "windows"

    [[libLLVM.download]]
    sha256 = "9dc2e3b56d8f296b59927312204d8bbe2e74276ce0e2380908240c903aa71faf"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2de7bfd998435e0c99e2cda2952c3046f0aec6e4"
os = "windows"

    [[libLLVM.download]]
    sha256 = "daf8beec0e9e63d7f1de44de597010a0866d69d4acd6a67b8ef929ab3bdaccb7"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef5eca91c980448c8dadcefc91d5f1b8099d7991"
os = "windows"

    [[libLLVM.download]]
    sha256 = "c9096a7e85c0d8ec0682a9c93816bb578dce92b85cbdaa71944b3f36cf327a7c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea28bdbd1d2f60d08dff5e9f4fcbea96e5093826"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "006e9df897f585406697adaeb8254a0c3548792d3db2b5bed1222196a64b6f0d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e07a3733bab2667170ba8105da4ee2ea8617f420"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "24e96a7b76822d49a30b997dca153f81738b49cb2fa929bbb75cadf57a11f757"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+1/libLLVM.v9.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
