[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3469cd0e6028021b58a41dfcdfaa559f8a407c77"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "4ec6cbb9bedbd1edecc43da7c2b595e55506ba572687fa6dc10e35d8dc89c9c6"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.i686-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28c9985b4b2aaa10a81ba40b4f534603a080e1da"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "b55d78827883129ef95bc9b247096512a08b0cbf323188a41e705f081f6ec137"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "26c6546fe24d6c4ebcccc609fbc480ec4ff17ea0"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "bdff3a438912beef5f0844650937e02f1fa8af1578660d9d860c093de7ba44f4"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.i686-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2e8d64fbea33cebdc8ceadbccd283bd66aaca6e"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "0d4551793796b7e72f0e00aa7ca5715d9e233a56eff0c1e9f72aa9c1f13f5eab"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61a69e0a8313531df8b7610d45f2bb9c3c56c88c"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "80df46b6bc284a2e2ffdead77c677f883dde80007f048935efce1ec61cf959b0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b992500944d78f0870a2c3c97650e064b071272"
os = "macos"

    [[libLLVM.download]]
    sha256 = "7b6ccf0d5dda0f901e3bee35952f307fd2553132673c7735eee59ad08f21dd50"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "79147d6953379346c64c2d158eb443989a2a1b45"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "cd21e1fd8db30d859809f431a5fd617034de175ce4de83e959904fa8ee1c0613"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "294a8eb75066d68d782c4e02fb1344a9c0e45f6d"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "4dff41d29345e217c7b19a8f40ea1b2a479f5172fb6c8716b8c4016ad7ce1bbe"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c66b06210c052c43131f938df5871334fe146ec5"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "e43b1927234b96b0e9e963969f4be291b7d416d2a93781a95b0fec5171091bee"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c746e782d1f1d5750446e7bc2f51a4ec0cdcd63d"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "063e7d2cdf473482352b009b81abab25b9a187aec4cd794fc98a491605b5a4fc"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.arm-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5bbf110d28b3937b47d1d23c1e651a4b09e2da2c"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "9d8e2b6a877ec352cf7dd8ddba586a11ecc4ae55998313f412ddb10e00e7f0d1"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee96c650accbea1f50d8c14e0c4934dc1d06beba"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "4e7597e5207ffea4ee716877bb6abee05e7dce10ebce1c523164078af560243d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1d282c11d4de46bfb043a2f3ba8825d83bad21b"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "38b6c5b30dbcf150b9feabf597e340616f981c2f639595d83536895aa74e978d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.arm-linux-musleabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b992500944d78f0870a2c3c97650e064b071272"
os = "macos"

    [[libLLVM.download]]
    sha256 = "da545a8e7f9173c65631c7d32ee2d8c4eed9b298057bb26c99276dce13388996"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "92c227ae18858dc4d3c242feca9b170f015ac1b8"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "1649e4adcf79f6d1d16b10252f21c977cf96aeaf6bcbad9175b13447e67f1bb9"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e18c3ddeaae07b8669ef9764fb6560287ec8e987"
os = "windows"

    [[libLLVM.download]]
    sha256 = "23d61070a51e97da1f58e7e161ed8320fad9706095e32656ce23dce675cacf5f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a7e1e48800226234578183574868942d9ebafa2"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "79d046d104105ee19d30b96f9fbe28524e1165e608178462d20b5265dfd18582"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.arm-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca5baabf4b0efa0bf9e38d30c302b563b257acc9"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "d04b9c975f57b28ca69bd47104c6677a427f36648d7f2c41bdcefc2f25c0dddc"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c39b27744ba5bf1fde09cfdf6c60f9dde8bdc504"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "921990f817fabcc011111e632e4dd3d54e03b106334614233f1415602c6545d7"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17b8f68fafa31553d45e60ab48aa9298dafdda4b"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "5e8fa03247b83b81d95bad759aba9c9806f129b328ad8448b3d07451eb6639d4"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.arm-linux-musleabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5db2149951eb800fed1f39b4e54f15493d1af15"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "8a6ffc3684601d775e8952477db0af71267f522c2e414f69f0adaeb0ce87254e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd11a0506d6042c0c7f357fe32b74a849a529cf5"
os = "windows"

    [[libLLVM.download]]
    sha256 = "a1b30b2cad294b641a059542167f91dde922c68cf1e192588eb5d1d0f8a3c4ca"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2de7bfd998435e0c99e2cda2952c3046f0aec6e4"
os = "windows"

    [[libLLVM.download]]
    sha256 = "b12adeacfbe60eba090a47f559f3bf6ca42e7a72ea892a6498b3f2e674a465c7"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef5eca91c980448c8dadcefc91d5f1b8099d7991"
os = "windows"

    [[libLLVM.download]]
    sha256 = "fdbd475cfd7a8d5d801819cea86d0e63a581a3f545033b9a61d3f2058b50cee8"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5e8cbfc8f95a6ddf032bf521518ab9095b1419d"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "937767777665c1bd79c772c2e0c3d4587bd4b824be10dfa4febd19184e2488ea"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79147d6953379346c64c2d158eb443989a2a1b45"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "f3313da0802b248c09600910db7340ff93123dab1e7a741ff85cb344187f2a03"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
