[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "503dcfe664095fbc198e2c05120d8760ab5e780a"
llvm_version = "23"
os = "macos"

    [[libLLVM.download]]
    sha256 = "d586a26a0e33ba38a609b8c42f04c1a44353652bda45ce55fc7aaa62094a4322"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.aarch64-apple-darwin-llvm_version+23.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f8eb6d3770d17f5baadb5ad8191f9434e25efcf"
libc = "glibc"
llvm_version = "23"
os = "linux"

    [[libLLVM.download]]
    sha256 = "2d7be220f6e3aa9f8249fd8a8b8caaef6945f39fa22db50e2864d9c0fe93377d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.aarch64-linux-gnu-cxx11-llvm_version+23.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48760fdd6d10955b7532ae949b02c3f3ff2a36bf"
libc = "musl"
llvm_version = "23"
os = "linux"

    [[libLLVM.download]]
    sha256 = "f5eb5966d115527b00c6cd9059b65476e8a77756f1cc1e658606177b0701cf6e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.aarch64-linux-musl-cxx11-llvm_version+23.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "a366169693d139e6c8f8706894382c4ee8985e5d"
llvm_version = "23"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "c0a982fd268261f2cc12c009bd91746b8471783a8e0a20ad1e192acd59a091a9"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.aarch64-unknown-freebsd-llvm_version+23.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9976e548f5321949130c2fec977112f181cd5ffe"
libc = "glibc"
llvm_version = "23"
os = "linux"

    [[libLLVM.download]]
    sha256 = "2aadd961ef0ed0817f4de478a50bb9e0e31c0bb69465066956eeea8f3483e003"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.armv6l-linux-gnueabihf-cxx11-llvm_version+23.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "136ec6395859ca5dd972e05e16814a02e0cf9cab"
libc = "musl"
llvm_version = "23"
os = "linux"

    [[libLLVM.download]]
    sha256 = "f51b293c1740c4f8317896f4a77eb12d5bdd6e97828a16d2eccf566a3755df2d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.armv6l-linux-musleabihf-cxx11-llvm_version+23.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd41bf1da5bf8b0184811a3f0cde87b28ed59393"
libc = "glibc"
llvm_version = "23"
os = "linux"

    [[libLLVM.download]]
    sha256 = "1a326668aa017b16299ed7aabbdf8c83de3fe0f258974056f2afd9fd76891c3c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.armv7l-linux-gnueabihf-cxx11-llvm_version+23.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b5438725118c4a68122d067b95b58ebb0f8328f8"
libc = "musl"
llvm_version = "23"
os = "linux"

    [[libLLVM.download]]
    sha256 = "f46b513cfa176a936c7a4cfada35f445a46ba2844f28a720507f0149fcd413dc"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.armv7l-linux-musleabihf-cxx11-llvm_version+23.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02cba917fdcaf870aed7516d84e05473620d9a98"
libc = "glibc"
llvm_version = "23"
os = "linux"

    [[libLLVM.download]]
    sha256 = "df9e715ea444f8a2aa61748e89ceee5e5382776da842716dfec0d6fd1ebcebce"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.i686-linux-gnu-cxx11-llvm_version+23.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea4b0df2b79446dda76045e96c36615e6b4240b5"
llvm_version = "23"
os = "windows"

    [[libLLVM.download]]
    sha256 = "43735ad607f736ce30221e0128daca65dc45a018bfa9e6e53a51fbcd815ae97f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.i686-w64-mingw32-cxx11-llvm_version+23.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5e1b7fb0dc2f27627321d9ba20eacf953e3010d"
libc = "glibc"
llvm_version = "23"
os = "linux"

    [[libLLVM.download]]
    sha256 = "33e3ab41504237716f81e344db4114cb64e2ffe12972ada3468b6337e6307583"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.powerpc64le-linux-gnu-cxx11-llvm_version+23.tar.gz"
[[libLLVM]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a77bb0440dcbc59dd985d2a69adf67e06f5e4a5d"
libc = "glibc"
llvm_version = "23"
os = "linux"

    [[libLLVM.download]]
    sha256 = "4b577d1517ebc529acae62a7603d53c84b7f1e8ff1e5f40ae6fa2b4cc942694c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.riscv64-linux-gnu-cxx11-llvm_version+23.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "42c14211b75e4dffacfba5435137f8c7ab242eb6"
llvm_version = "23"
os = "macos"

    [[libLLVM.download]]
    sha256 = "168201bf37db39d7cf81a2230dd50a3810cc41003066da71708c769033afa03d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.x86_64-apple-darwin-llvm_version+23.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ca82ece71e0192a3ac4f0864f170eeb5b080c81"
libc = "glibc"
llvm_version = "23"
os = "linux"

    [[libLLVM.download]]
    sha256 = "4094cf52b400bb63024d45b02cb719f3db7cc41aa14a884670600dab66fb6ffc"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.x86_64-linux-gnu-cxx11-llvm_version+23.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ca82ece71e0192a3ac4f0864f170eeb5b080c81"
libc = "glibc"
llvm_version = "23"
os = "linux"
sanitize = "memory"

    [[libLLVM.download]]
    sha256 = "4094cf52b400bb63024d45b02cb719f3db7cc41aa14a884670600dab66fb6ffc"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+23.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29fc4c7b76668a1109f50db4718dcd8959d79dcf"
libc = "musl"
llvm_version = "23"
os = "linux"

    [[libLLVM.download]]
    sha256 = "84ea7dbb559250c4ecaad13c4be8376a1754af4e03382e66bbceff467442ec0d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.x86_64-linux-musl-cxx11-llvm_version+23.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "011944c7895b4ecc5b545cfa0d72a0869a81aef3"
llvm_version = "23"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "fae4a601e35b0a866e4081071c1ccada4fea4271b813b6974931e198ad21f1dc"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.x86_64-unknown-freebsd-llvm_version+23.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "266aa0974a0e0f74d26e35bc2e984927e920662e"
llvm_version = "23"
os = "windows"

    [[libLLVM.download]]
    sha256 = "6481aebc48613de9ff0092d9d3db0c041af11458ca3d0bd9190a396a055bf6f6"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.x86_64-w64-mingw32-cxx11-llvm_version+23.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "7677db09152c17af5ffc45bd2eb45fec15a5ba24"
llvm_version = "23.asserts"
os = "macos"

    [[libLLVM.download]]
    sha256 = "d0ac0b3b91d7e6339c0992500fef7497c1013f957c798c7aa3f3db1dfc7fdbc1"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.aarch64-apple-darwin-llvm_version+23.asserts.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9cb705d0d833478f3d32e6f60da2b5a2c5c7593a"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "1f48d4c3b0545617f0c7904026a3de498639adb6b9486596252a868943f1a1ef"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.aarch64-linux-gnu-cxx11-llvm_version+23.asserts.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7a6a0592b1a5545e75e55b27e5080d979e8a3fe"
libc = "musl"
llvm_version = "23.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "3370188ce349dfc4205bcf8d1c650a35219e2fef6e5f0c632d26e4fb37a253ab"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.aarch64-linux-musl-cxx11-llvm_version+23.asserts.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "e0159d1a49cc4153f4f278718678f2670d9301a9"
llvm_version = "23.asserts"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "5819c44a85b00c217158c987c832666c059f6310cfc3379dc356124aa38bb049"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.aarch64-unknown-freebsd-llvm_version+23.asserts.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1a25f523e7bbffad7a0c9f2bd6c72ea6412c2dc"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "2bc13e056888d0341d1dee29436d6f9cffe5b310c1570580794a4f6c6cf8e049"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.armv6l-linux-gnueabihf-cxx11-llvm_version+23.asserts.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aeffe74e346bb3804312534f3948975042e01a18"
libc = "musl"
llvm_version = "23.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "900867a1d0ac92488ccd782087f79a632c3b84f9ba16a858c60733ed86119a95"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.armv6l-linux-musleabihf-cxx11-llvm_version+23.asserts.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c79e7a619f6d564ee4c2ffead241b13e9c0bcf9"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "2474f51833b05ad2e2912d7cb6c7cbece0724368f1996f29ed8df21288620a06"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.armv7l-linux-gnueabihf-cxx11-llvm_version+23.asserts.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "469bc7dbd4e83ee2759f3b5caa0b4d063422c4ee"
libc = "musl"
llvm_version = "23.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "8c3a710f7d3ecc9924e5f310fb05e9f69fdf58e59789458595628cfdca4e3341"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.armv7l-linux-musleabihf-cxx11-llvm_version+23.asserts.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1b46460d2729784dbda285daac445df599b14560"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "12e794beb619d074440001cc24555cad6b908f4dfb3e386fd9cae16fb7fbab36"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.i686-linux-gnu-cxx11-llvm_version+23.asserts.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30534f6359b30391f7e7c779b3f6ffc389eabe24"
llvm_version = "23.asserts"
os = "windows"

    [[libLLVM.download]]
    sha256 = "ad0068a18fb6a31fec5c59038388705d57bd9ffb9d98265dceb2f69a0b2e5595"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.i686-w64-mingw32-cxx11-llvm_version+23.asserts.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "402f4375cc7278efcea5fc02312de05c714449d6"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "886f8fc70db9964e5783d217cf662538e1581e55b027594760625501348ee95f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.powerpc64le-linux-gnu-cxx11-llvm_version+23.asserts.tar.gz"
[[libLLVM]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f748c9515812c496bb5b9484a7c28dc7f17bc79"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "9a92453619e96be29a7a35bf3bcce0c3984bc97ca477c3a0bfbce283f54e22ad"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.riscv64-linux-gnu-cxx11-llvm_version+23.asserts.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "cbc53799d20b13912635dfef8397e56cae5ada38"
llvm_version = "23.asserts"
os = "macos"

    [[libLLVM.download]]
    sha256 = "ec030edc0a4c67c6401c3601d0f1c3caa4527d25aad31d3b4d7ff9376879c743"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.x86_64-apple-darwin-llvm_version+23.asserts.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "adc918b57f47aee8c6512e5466697a11f6859179"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "bcae1cb057a22908971d34b39493fc567957f80f8adc3c22903eea7ed7c221b0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.x86_64-linux-gnu-cxx11-llvm_version+23.asserts.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "adc918b57f47aee8c6512e5466697a11f6859179"
libc = "glibc"
llvm_version = "23.asserts"
os = "linux"
sanitize = "memory"

    [[libLLVM.download]]
    sha256 = "bcae1cb057a22908971d34b39493fc567957f80f8adc3c22903eea7ed7c221b0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+23.asserts.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2913af94d65a7b5caa5abfd8bd83c74866c46293"
libc = "musl"
llvm_version = "23.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "36f510294fb5aff1b4812dd4663c919c0bc185c196729ec582bf219a0b1dd8e1"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.x86_64-linux-musl-cxx11-llvm_version+23.asserts.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "adbdace6ba6a093fb56fafb55ee6f79fa8f99642"
llvm_version = "23.asserts"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "5f2c54c0f5608b798f9567e129a60ebd4e3d7caf90207cfbe154f0e15ab277a2"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.x86_64-unknown-freebsd-llvm_version+23.asserts.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49ec24ec6625658ff725d942beb289a3d7029ba6"
llvm_version = "23.asserts"
os = "windows"

    [[libLLVM.download]]
    sha256 = "bb163173ea3173c7166b0b02f09eb18c48d04b1e22a0161065c9e5ee671ef22a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v23.1.3+0/libLLVM.v23.1.3.x86_64-w64-mingw32-cxx11-llvm_version+23.asserts.tar.gz"
