[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "72e1b2e3669ea482946af3a24ee8e41afd11f76a"
llvm_version = "18"
os = "macos"

    [[libLLVM.download]]
    sha256 = "977d870146ed92c425239dfac630b4916cd09c82ab0ff8cd58d672ec1c5eda19"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.aarch64-apple-darwin-llvm_version+18.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f44caa9e6677c911785cc44ffda2a00f43fc94c8"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libLLVM.download]]
    sha256 = "51cce80e6602e519860852c57301e1b9ca5c61cd8a36e31df595f5ca818fe9ee"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.aarch64-linux-gnu-cxx11-llvm_version+18.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d8ecbe09503d630bf33eb6203bbfc7a2a558248"
libc = "musl"
llvm_version = "18"
os = "linux"

    [[libLLVM.download]]
    sha256 = "98ad61821734155cad152a3f18a4c72e3d461167d3404b4cfa512f15ac2f83e9"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.aarch64-linux-musl-cxx11-llvm_version+18.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "de05112fe67181c13cc2fdf6e2b54984d8fa1563"
llvm_version = "18"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "d89a72473bff6c013760d4557ab8025ee9e5c4a47a4830e1fc82d0db4a525669"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.aarch64-unknown-freebsd-llvm_version+18.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7e834ef26353ab8e02c8c48731084cb1e85d8e8"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libLLVM.download]]
    sha256 = "435a62f20f191b68d1efef1f4d99bb08c80af20c2be9ed2022438724acab51d2"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.armv6l-linux-gnueabihf-cxx11-llvm_version+18.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8dc96a66b371f50e7ee4583b319c959f2135a66"
libc = "musl"
llvm_version = "18"
os = "linux"

    [[libLLVM.download]]
    sha256 = "19cfabc4b237b51ed1c4f9a3b1dc7320c8cff4cd06a04f71353e18f9140b4b43"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.armv6l-linux-musleabihf-cxx11-llvm_version+18.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48d50c8aef272dddd3940b3f14b0c90f5a91919b"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libLLVM.download]]
    sha256 = "50e572e6798b5b0a4340cf62cc05a3c52d9a743b44cd25938f2f77815ef8b06d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.armv7l-linux-gnueabihf-cxx11-llvm_version+18.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c53ef60ac3ddbf8bcfacd88c0ff12575584067a"
libc = "musl"
llvm_version = "18"
os = "linux"

    [[libLLVM.download]]
    sha256 = "2110a59083e616d9a45b116a1560ba0187e61d735d6a07fbeea0bd6596638acf"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.armv7l-linux-musleabihf-cxx11-llvm_version+18.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c94e29d0274e9413b923632ff2658199af024ce4"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libLLVM.download]]
    sha256 = "f2b509595183858a0adf63d5e4f55fe942ea0496b38eab6074ddc09fb112dfa2"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.i686-linux-gnu-cxx11-llvm_version+18.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e592c15c3b88d2c45a1b568aee47bacfcb631049"
llvm_version = "18"
os = "windows"

    [[libLLVM.download]]
    sha256 = "474d66d0d6cb36a7b37b7eaff38edede6cfed53c98d37d844dad42911d568df1"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.i686-w64-mingw32-cxx11-llvm_version+18.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8e6bf469088e5c9e470e26c48e86d8844796589"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libLLVM.download]]
    sha256 = "51b8c562e8ea6b4d82ad9b1f14535c85fa600c3ea8a57133eaab6fec7970d025"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.powerpc64le-linux-gnu-cxx11-llvm_version+18.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "763e548739da0b5737fab82797880f46dd808016"
llvm_version = "18"
os = "macos"

    [[libLLVM.download]]
    sha256 = "1384d37a120e21f5b844ebac6ab11e1335490daecbd2cd1a80b88b012f6b724f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.x86_64-apple-darwin-llvm_version+18.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55c7927a59d528badcf4d0a4263c9d6f93ca7c0b"
libc = "glibc"
llvm_version = "18"
os = "linux"

    [[libLLVM.download]]
    sha256 = "bd61b6533748035b105cc4dcb7c25ec19478749ad79049fa428f88f5776d1a28"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.x86_64-linux-gnu-cxx11-llvm_version+18.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55c7927a59d528badcf4d0a4263c9d6f93ca7c0b"
libc = "glibc"
llvm_version = "18"
os = "linux"
sanitize = "memory"

    [[libLLVM.download]]
    sha256 = "bd61b6533748035b105cc4dcb7c25ec19478749ad79049fa428f88f5776d1a28"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+18.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63353b9efbdcab1352d3a840b2e4afdd274802ae"
libc = "musl"
llvm_version = "18"
os = "linux"

    [[libLLVM.download]]
    sha256 = "b18478ca8a1109a006ade6e4477a28de5b8d13180806dc16c6ff090d6a365ecd"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.x86_64-linux-musl-cxx11-llvm_version+18.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "c571bac780c5690ae5fbf0611911a297c9026b01"
llvm_version = "18"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "4d731530bd52bedb9224e0ec6b8a5009bd2f2636f937ad87312b8f56070405a3"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.x86_64-unknown-freebsd-llvm_version+18.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d8f65850367f9a741b2a04c59023210e8fde34f"
llvm_version = "18"
os = "windows"

    [[libLLVM.download]]
    sha256 = "eba42548104ebca17e1a34da55d85bab65aaa1a861636b42b0ed50967e3d1411"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.x86_64-w64-mingw32-cxx11-llvm_version+18.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "96c71180ba0f14b719e4dcbd77d0d534bd524855"
llvm_version = "18.asserts"
os = "macos"

    [[libLLVM.download]]
    sha256 = "e4c6a88eea58220d66b8e8a8a0ce984dde0507a9fee73aa7f54900c1101b7455"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.aarch64-apple-darwin-llvm_version+18.asserts.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b443464956e8a48f658e8876b0b59088e466825d"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "46873fa2f1f91a5a86af0859921bec8ddb5318955861065f5e99783e9386490f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.aarch64-linux-gnu-cxx11-llvm_version+18.asserts.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "974e68fdc413eee927c9f2bcf554320b66781a48"
libc = "musl"
llvm_version = "18.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "dc6a026414ac90a315ab4f4b9c0e09e1a7da727acdaad0ceffd0e39e19bb8af7"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.aarch64-linux-musl-cxx11-llvm_version+18.asserts.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "37f6466d771eee696bede56bb2dff7283408681b"
llvm_version = "18.asserts"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "cb8590b0a1a2b42e634803ba24b3c2d705ba21ea520addbc035cc27bebd36ca7"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.aarch64-unknown-freebsd-llvm_version+18.asserts.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08d67240701805e3644739a60011b912f12512db"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "464eb81d98bd0f3aaa5a404647b98a4eae1f5a6337825830d6a87791bb403954"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.armv6l-linux-gnueabihf-cxx11-llvm_version+18.asserts.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "510b86788a72ce92a3b950fc110fdd996a257b4b"
libc = "musl"
llvm_version = "18.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "abb61f66106d93f3aea491f1bd2147412875fb4d19da9f64c5c5b790a385a1c0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.armv6l-linux-musleabihf-cxx11-llvm_version+18.asserts.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2b47b8cd6612e7eb1af23075087f7d08a25aaf8"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "811fbcb856dc6b170720764612a5b0a136e89c6a23cb2cb58877892c77460ea2"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.armv7l-linux-gnueabihf-cxx11-llvm_version+18.asserts.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35b74f756e84d5825a24ed1fc7001d0080ad4706"
libc = "musl"
llvm_version = "18.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "f94c4b0d749b032dd502268a2b33264fd1ae88a6bc620ce528c0072c11e9eeb5"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.armv7l-linux-musleabihf-cxx11-llvm_version+18.asserts.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc81d964b518de5e5ecbda831368e4cb6ab4def5"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "927ca6e913739ae505d9c48025f1091cd80ea389d542a7048c9a4776c112293b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.i686-linux-gnu-cxx11-llvm_version+18.asserts.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08afd5439f16421b6765dd27480390e9bde3ec82"
llvm_version = "18.asserts"
os = "windows"

    [[libLLVM.download]]
    sha256 = "ddb37a2b6432df5e0be25126b6bfe6e9953be217ef6366e035e3c6129f74d92f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.i686-w64-mingw32-cxx11-llvm_version+18.asserts.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78a4171c76f9510424f4da7ea24b2bf38c8a8aa8"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "2bce355ee9a83040386975966dfb04322642440a089fb9b0d40489038f30d040"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.powerpc64le-linux-gnu-cxx11-llvm_version+18.asserts.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "63684337ab74ffe50b2928de1ebcb7effe28bb7b"
llvm_version = "18.asserts"
os = "macos"

    [[libLLVM.download]]
    sha256 = "06b743e9a41ee908507cb9710162d77090d3a955be480ac49e1deee50e85f745"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.x86_64-apple-darwin-llvm_version+18.asserts.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "86b61dae5125647de973cd5d5c22d4a373f67e5d"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "5e6fba5cbd0373669a928699c3d0f870d05dd3cea58fa889ea04ad631305aaab"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.x86_64-linux-gnu-cxx11-llvm_version+18.asserts.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "86b61dae5125647de973cd5d5c22d4a373f67e5d"
libc = "glibc"
llvm_version = "18.asserts"
os = "linux"
sanitize = "memory"

    [[libLLVM.download]]
    sha256 = "5e6fba5cbd0373669a928699c3d0f870d05dd3cea58fa889ea04ad631305aaab"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+18.asserts.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "792a6acfc1cc945fc6f0da2c3e541ad9b1f8a2b9"
libc = "musl"
llvm_version = "18.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "bc5143c3d662bddedd14e086fa97fcde1d27200340b1307d2288d4ccc63ddf43"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.x86_64-linux-musl-cxx11-llvm_version+18.asserts.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "b42debd2a633cb98e74e4edba2ac4df18cdfc9dd"
llvm_version = "18.asserts"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "d6da0b621d15347786da6ea9c65af2b441ef998e30bc65442f3369337048300b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.x86_64-unknown-freebsd-llvm_version+18.asserts.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b425357349a44761a05cf7beaa134c0ed2b77b00"
llvm_version = "18.asserts"
os = "windows"

    [[libLLVM.download]]
    sha256 = "cafd1ea4c2fe478502e24df607f7100338a5b73b824adb4ff35312fd581a0871"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v18.1.7+6/libLLVM.v18.1.7.x86_64-w64-mingw32-cxx11-llvm_version+18.asserts.tar.gz"
