[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bdb8616d9be5625b0844bd8853c04c18fe82d721"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "08301d25dd7efe705e95d5c22d286a97438f63b0235f878822dfcb3ee5676873"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.i686-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07d21c828790d636b11f4d64d7e04132e76e7208"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "8d99bf9645f3306af0dda93eab0eba243f6e2e365f8e9783fc97abe80e69c257"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0866f798cf672bc4234e99ed950634acb78bd6ff"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "c80df0e204edc33c31fedd5d5db9745ba4dd0ccf6e4bb867af83abcc34c8969f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.i686-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3ec0aec4ce0cbefabaaa11c030fed25dccf8a91"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "87bc7b016eb3fe28c72246cb8718595459239174736463a322a8030126d5744c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "62d0079dc6e732706ac2f640adb344ee2a7ad316"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "50dfebbb7771adb88f08e68845bc1ca74efc32acfced6d507d0decdce053d539"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "83ca1c9b14d9eb8464532191293d11294a94c6f4"
os = "macos"

    [[libLLVM.download]]
    sha256 = "4e5cfc2414331dadd3a56736e5b352ffd6b6dd4dabfc7534558f26064c551c7f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e07a3733bab2667170ba8105da4ee2ea8617f420"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "ae5dd1faaf5b5654bf4ae170844f6b808daa10f03e8fda793a2cb3f9f0757296"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5550887957c5e3fbaab6758fe7719c1310bf9ead"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "7dd1f2c2ca8fe6b60472b03e8edc0c11be85730f2e1d6888151d5d29f5c42ca7"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "964a30acc8225775a767dc6c0a3dcad82502d8bd"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "1099718e4f41f53142c9f46ad996207173bbdbbb5aa0f9965bfb592986163bc1"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d97a4767a6fdcc18116f0e56ba63073eb06b690"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "a1b8dd02fcc1817056eb28c52bf008369a41d0e19fa31d799fb6055ec5253aeb"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.arm-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f5b9d97ad66344b2fbf734cd6cb862112e0fd0a"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "c0fe83a7807c8349b30b5a6bba7b1cdf008e7e2cfd5cf2c6212276a10e01b8c9"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "475580ad6617c00c19ba8cefaed76a70df51c3e7"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "a6c6f5d14fc395d639462fa5d13332d26574029adbf857a70c1bd87188a960da"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b0d0158dfb5b8fcc9bd4050103082cd878921115"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "34d1b881a2fd46277f932be29d5158c0ee6f91a6ccabfb794c308d0bd677efb6"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.arm-linux-musleabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83ca1c9b14d9eb8464532191293d11294a94c6f4"
os = "macos"

    [[libLLVM.download]]
    sha256 = "b74362003889ec33830ee66087ef83676fce0482f0bb15c876272e015383f319"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cee8bc8cba9dca1576f94f86730b4ebb6f5d3fdb"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "b1507eeec31f8d8e13be49caf613c213679849a73e3dfe4390ef253e19efd7b2"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e18c3ddeaae07b8669ef9764fb6560287ec8e987"
os = "windows"

    [[libLLVM.download]]
    sha256 = "d412ea4e14daad625849060b245c0c6b9bc697ff902f4aceae09c4aa56b22f4d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4c6896af077ea012988c27772c0328c1171b7f4a"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "680c69c2b88e3067c5c0012d69ffcce9424e2c9b21141b29b7cac2bd8d0598c5"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.arm-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48c79272db07213ddc90c026b3e028f0bade08f7"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "a9940fbfbc3110c2146b9e7369e2fb922c96f2a745faf0e87db006077bfab784"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c2ef8c4fff7915953afef10cd7138f7b21e9ac6f"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "cd5a9ba6443207dd01a773f85ad7810cbebdc5c4fb148c7a0f8911be3b8a04e9"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd67de33c844bdf0b51f49998ca38c672763f578"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "2f87a947a6de691d43d44a1afc78c8dc1b7e0e3afed5cdda37cb8af37fe38bb1"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.arm-linux-musleabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f25025029ad7a1d9db8618b27cfa71e96b3e8962"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "6ecb3f25ed6de5db2e4167f3a0b45b0ea2fef19e5929e0ab1ad8ab2c02fda15e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd11a0506d6042c0c7f357fe32b74a849a529cf5"
os = "windows"

    [[libLLVM.download]]
    sha256 = "3bcf645c7d5a9da831825315e56861cb3c56b4725fd527b5c9afce76b1ab1467"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2de7bfd998435e0c99e2cda2952c3046f0aec6e4"
os = "windows"

    [[libLLVM.download]]
    sha256 = "2eb7b9b462d863dfeb0e719d9774476e9bb53f840867ae659baa7cc073c12685"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef5eca91c980448c8dadcefc91d5f1b8099d7991"
os = "windows"

    [[libLLVM.download]]
    sha256 = "9250e55906df5f1eae8189ad5fa9d801d95ad73f10e064b5e08908ac4842ca9d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea28bdbd1d2f60d08dff5e9f4fcbea96e5093826"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "1f21f436247f8fac8be2a05bc822d756ea9508a2d445acaa82d82cada2316eec"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e07a3733bab2667170ba8105da4ee2ea8617f420"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "a91a822cba1e812d5cd2ccda283e29c1da1ad32dc888e57845152cbec353b57e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+2/libLLVM.v9.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
