[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "36f3e94af13ab6b30a54cdcba58906fcb2ceef65"
os = "macos"

    [[libLLVM.download]]
    sha256 = "ecc3fb7b81cf4f971eb25fcb70f23679202f7d1f3c5d4bbe43d43522672bef5a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.aarch64-apple-darwin.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "963db9c19c09382493aafb65e6b1bbb4132cffba"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "0dde02d0aa6322e793d6753796134e3fb5bff733e5790be92030e67a142fc99f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d64345fe1107cb91c81c40f6d0bb5ed8ff56fa3b"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "719bc6870a0ead501cc0864d76e0fc2815e1ab51e5aca8fa1ee4de9be636db3e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f87238f5c8e5ac4f8378b4d9d1586710dd25a5ac"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "d70ead051b2fc7cc494456ab930bb5dbc1e0c9b464d4c5a7d13af12e5aa34ff5"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "078219cf7807fa029006330990fd683ed791e5d9"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "57795af455c996556c48e849d9310b6bda594e86b6c4bb969ff84c02d44aa898"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72a9851cad020db0b1f64337bc1767d005bc6515"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "764c7e1858d2ff80159eb2953baff6c4dcf218e13a740ca5075acf3a91c18cff"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b4fb3fe6043b1a01813e845f87be8e7675d7820"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "4db1d5bee1df567686df77ec4c7155aca5bed7d15c3685d885eb80dc36d49984"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c1979d548b25c8381a48e4c4f5c0669abc424e5"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "4434838fb2b9046fcf51532146209ec00a169d89a8a540a9d5b76ad6638ca57b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27ca739793da21d027bdf1cb2996a8391bc9ead3"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "2afc0f4c480b317dd3f54815259352870238d4b44b4114682c755286d56dce64"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0f3891367c5757bb366700c3fd7b57013ad06e0a"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "274ec9bde7a89264b916c215f689d4da6c38760e1957c5f194f825e5172a3feb"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2341af1f369ece9ba444d27ff7ddf1f2175b5a10"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "00547569aa498d7b4bb43d328c4444b841b91f000c015e933bd332832a7a4d16"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec36a4fcd13531801c37c8e9db60c3d27914dac6"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "529d0b0587ffe846eea605d271fdd3f8b4efec968ebe9713d31646d61d2bebef"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97495bf2cceb55a56fb9454c1a62ca99cbfbc0fb"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "0e21ff58e7657de3d6d4c1f8370849f5b83ffc7c9239d9cd0c0f9616d7f707a2"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38e9aec3b04da232386c369c0142a9320381326c"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "5a3a63fcbf73a5ee96777949a55f65db69318df0f62948c386a675373343a8db"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d055874dea59a65183d433494ca9be14fce6825"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "fa97d85508129298c0f9144efc2b5ba547f8f9c5f85e15f7a106e48d4c45a91c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b910c2dfe2b551a826448101aa34d33326bf8e52"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "2d9fb36ec378ad5e561c7149b54ff04fdacaef61e3ec44d15fdb29632b671575"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "547db19179a0acb4e2bebc203f989ed93e72e469"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "ce8d9e93b1ef4a4d80677d6e18be9eb499c877cc5f7a3292dab4cf95ffe55153"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d4b18484da93e3c544114a41ea9cbdc9a6e7f68"
os = "windows"

    [[libLLVM.download]]
    sha256 = "ec427a07357166eda6aceb9046159a0458b44a759e35a1d331e8735ba7b74a06"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f34587652a1f3d50bbac9b61b70f80b767279a94"
os = "windows"

    [[libLLVM.download]]
    sha256 = "a427cbeeef4cf8d6bfab0955f4706b70e164b25328cf51b7c879a989bb0a40c0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67bde4f994020939bb44cd84b4f46ecf0f718a94"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "9679488cadb70dccefbf09e7978275e8e84dd10dc134e2ad453712cf970e1f7e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0cccf48b7352b08cdd86c7223f5cc243bdfb697"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "9e7b440fc2eab0034e2b109eccbb78f963d716cc89703c9ee4442e1da60f9f53"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "bdcf48f59d7187ad0dd9b2fe4a8af61419cdb2da"
os = "macos"

    [[libLLVM.download]]
    sha256 = "ee9f2f3a39505a7a2328bd2e5fc4f6c9f94347f36e9b40a7e994dc48f58d6357"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.x86_64-apple-darwin.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "430d3cf15ab0b98962920bf81b3c2207714d6afc"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "60bc8011b410e5a6d6ed9999c42b7634fa592343104369213b17b31e259d7d0f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "92c24ad5646d33076275db4537aa176f334f220f"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "3bc83bc41dc645c249c53a2d42485b6f53550b0425644cbeb647f19ff1c25183"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fed67c02d9ec4c81aa0ae1bcb0013d8e0158c0b5"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "a5839866d4a9a814951cd689af5519e0cf858b29e56c68edaa93090da2c99a57"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2318b929762d7755cfe0f89a83b28ba0cac9bb0b"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "74b4bc9a2ea965ad458a71912cea68c998a73b3b20219baa62c83f5ced5ff865"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "fb2c0cc1fc3a4ad5a0a5637903e42b6b5a5465c9"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "a24743bd4a94a30ba4b3c0fa395fbb2c70a7221f686c67bef0695691a9faeed3"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "863f2f15bac25104f2ea5f8d3dad126e43a57989"
os = "windows"

    [[libLLVM.download]]
    sha256 = "b31a4fde30ba6cb528f3caaa31e1fff1f8d954b18617ef0be8513aeeee0cd904"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8bafc8cc8b557c2ba00bd1a6caf68bb6bbbb11de"
os = "windows"

    [[libLLVM.download]]
    sha256 = "5bd963ffd1ed399862a2a19ee93d84d754c4a40dc1ab70d9f9958bb14d461b09"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+3/libLLVM.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
