[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "a80197794fce893e64e80b886ef24339c2c07ce7"
os = "macos"

    [[libLLVM.download]]
    sha256 = "e1f1c60620ec48c1757d1c2ff85e485e4d1114fe217c9c09253f17482f979ba0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.aarch64-apple-darwin.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "828abcc7dc61af327e9df5a1136eeedf48b70c80"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "15b14c244c87fcd1a396cb9ec6eb280e552d33e115067a0ba9f9de55318db0ab"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3cc376c469ca89e4b0aef6d4c70af92b610278ec"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "80f1bfd8d5ff8ca4ff1aac7c605993861ee561fb5988b7982e3c838f5b5f4670"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "00fd8d4222555acd62374a825d8158d27347c036"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "b3ba26d138d1595e9730d171ca425568f43e3f13d78d0d221cd5bcb01fabe0d7"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75d05327de2d83e4ff06d4b9068e0872bd72c6c8"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "a0bbff503238563dbbf646837e75b3784d8d1d4a8d44a7ab5f6eb9dca5986cf2"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e14c7578a1a3379d6f1730be3e427a21116097c0"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "7d683f8877b3ce1fa33abdbf1937172c75317bb3c1bc787c131945492a7bfc11"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22e3a39a0e10de76e4bd3b9dbf56bc59f74e4fd4"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "1fd734d8d0c95f285a1384e294b1020f4adfea0939e484bba12b7d2ca34501bc"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eac36156a29fe2d7108a7d96ea67e3e9fa10a6c1"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "60653aacf0e6a50da7adcd8307a68445e9c4338b47c2826700b40b54affeb26e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce5c945a0ba8ee214acf76a2f9e41a7d88ace04a"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "26af0366e3b3e642e30daa33e7dd2da0a026d3a79e28fef05aff824dde6ab693"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21a2baff458c36f899da17679aa89510edbc6d26"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "a73d92554a7a4804fb87745133a2612aff82a4ee8aa4dc35e659ad28c14863e4"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3818139eec4b3fa0c59295fc8424fc9a8d6b2f48"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "8007587a7083e0f1ec37fe533be5180294e04907ff5303f58e8d9e3b6c03e094"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec9b32000e982748607d17b9ccf1250077d42a0f"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "6811750396c508c075544e22ab3df264302e62b07772139a3c20e3bded6a8e72"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28e420b4311349722a06af41f8476d0a554c523d"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "570ff292022b39a2241638533b4cad399cb512d5aa9a50da76544ec9081a089a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95241da12c230207f348cb2d02f0ec90d80cb823"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "9b68787384ee88aa09ed1e4d892bf942e9349362707ce88c6db0e36d8fb7348d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b3508b979ab0b4ee3e927bd3f0e4547dd0547c87"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "583f8fb73f927690965fbbb1016da8300c1057bc2b72214ad65ae2b586af8064"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c9b6db4d003388016dbf7318eb548c4e7f858b71"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "8b2a2e3ad18ef5369a90f463ef3702bae4f12401d6b1fdb295a72a63b1f45862"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "011dc549249233c46ec48da0a44bcf4c54573d9c"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "1958699cfe45f63d26132dcd6fbaf0ee987bf884e9e75713a7cca697e2492b2a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1bb55446046e78ec8e6876224a92f6b02cc8ae78"
os = "windows"

    [[libLLVM.download]]
    sha256 = "951d8ca02673f3c0f26521f29584ecfa915cbd541ea9c585d00b4e5e6148819b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a78f8fbc9977b211620676a616a650e1dd9e79fe"
os = "windows"

    [[libLLVM.download]]
    sha256 = "73dba6888912314e7fe84cb3bcba749c8b1dbe9144bfed6d20d7961f02c82847"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0535719755991c76fbf3481d30fbcd4f1dbbe278"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "a4787a4eb33f1fd43c4c2142fb18d6dd4ca49431ca6cf2b0fc2f7bb2ac2e24b6"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9874bd66358da96b9f2034b5363ccc423ac4d230"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "1b0e211afd7a4e79fb7a6e6603c0c651455706954c7143550569e1eacfc39392"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "7adb364f92bb06cde6b9890f5a3a331903513f4c"
os = "macos"

    [[libLLVM.download]]
    sha256 = "ce3e738ecf6fb8cc047a5dc065ed0bb2807c4b8436d7066aecc557425bc8124e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.x86_64-apple-darwin.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad1b749603bac97a2e9ecf9352e9d5f2b8eeb9ce"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "98404a826a0e1c02bf3fcd0e5fe6e551798bdcb4a373dfa63211c57f183077ee"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f44b01d13eae3541a1bdc7d13b221a1c4c3cd941"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "a537c46ed98fd09d7e41116f8e3676fabbffbab40888c318c14f46de12274330"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fc7d23699b112cdc326249767c93a91e1fecfe8c"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "37160409a3d256ccdd84128edf82cee1824dfa99bc8a78b909820bf13709e0dd"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dfecef619afedcd84eee442ecda1a92432dc963d"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "b18749c3249dc20a67a306f76043a453e921bf3f9c365e62d9c66b3115b4e2d1"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "267dced1f5a4657c54a6f01628d598270b6d85fc"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "17f553ec0c48ab3c0aa98412e2e243f4d14bdd3875f29c4c11eb793a710810fc"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eba8b1b94b23e1ff2bba0128b3da5a18f677510c"
os = "windows"

    [[libLLVM.download]]
    sha256 = "97337ac4ff842bf9bafe4784475adf45279b77a42e342a06d3f8e81254f63c0a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "714fbdaa74e8306578d30d5d6cf3d0140de0b6c6"
os = "windows"

    [[libLLVM.download]]
    sha256 = "06af3720844b32874e6c707190a3afc25c6f0afcd248eed254cced03b9d378af"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+1/libLLVM.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
