[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "8bbf64921d8ecd9c8ea3adc0df451aed95d81d57"
os = "macos"

    [[libLLVM.download]]
    sha256 = "06631b002c33f5373465690266434fc38a9ac2a1d9172f6e049ae531f6aff1f8"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.aarch64-apple-darwin.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "905f08a9e2ed21e616ad8fba0e479533d67d53d0"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "5d4cb9e2eb4a1fbc70862903617964d42f3778731f58390b4db6c4349983a218"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2804ba32eea7fbddc46ad06e273070a07765d11"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "dc6f8fa74409841cab5e970cef2083dc6b20e08552d973b128ecad6510e22038"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "54699d04586fb412400a079825030164a576fcde"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "216bc026d79b39e7ad5a9cd64b4f2f4446263c6d360a8caceb4f67f1c6132588"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48ebeccef12be4ad105826eb4c86f41531b7e054"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "71971e60a7bf7c2dce17e7660bbe7dcb6ba6c6784c9cc68d580b4eb6d9e079da"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "54c27aaaed3c5d5eeae7bf99f083a255ba8f6c54"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "3428bda09811f1a428e2886415d2700708261a87687a30a87d151db723b704a6"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c76480d16cd7556cd8c159395b1f18cc01143c2"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "7b96ef21e9f0f1fee392d1530fc2d1030a6e40600fcc070fa53a4f3eae0828e3"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c5c42359c0f5a2625356efc040ece2edac46352d"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "e70fe7d3837daab7762cc75b6b306f84bd1b7635d5c897b36cf998e4b54c87ec"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0cc38276b368ce9455c73ec33ec2da7bd0395436"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "3ce68b9e5d90f96a4db4499f3e45520bb1455daee13fefcc502197717500d418"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7ae975d238a99c274e805865788c973cc5abc0d6"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "878dbc0683c77df569e63886666c40e38dea8c009a86bdeb26bb6abbfb3091ef"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6aaa639a24d2db39e6f7ee279e4bea52f5492101"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "03e5495db0abc755016ab3533834ece43f80cc2961e9f3e2b18b90d73375d1ce"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90aea15b6e704eb8a57a0e52d2b53526e6fbd89e"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "e62d58f8a6987fa130dde7f063dad05b8103516d97532a88e553912dce12eed7"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19e2e5571cea554e1e0955d05dc608f94f8502e7"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "89c941eb1b94deeb38fd1ee67644e7fc36c64b44c2d7450f8124bdfd241a977f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "632b770de4589c856e5dd5dcb136063a47a88278"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "2fd0dff20b674bbd52a75dcf6d7823b4fd72c161ead85a015a140468a7fe1cb4"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40565874b88c31a0d0b9e6f169c47223ae675f6a"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "f0c6689c01bc6a920b1e010cdb7eb13da2e3ae20fb5b404e28e050cd53773cd1"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e78f5f024e5b725d80b2cd03a451606742f9cb81"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "b2e5d6ed8aa21bea913e764ea80d8accd1bb47be494b57492243138cb4652a72"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99e3ecf2373d82823669b7722001a654edc0ee1a"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "d7e8ead8b831dae546bbeb5f274f21c46882a170ea61e0575c45ac82f7ffdfc3"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "01e46186a82f8be78b26ae2f2e45afacce02e17b"
os = "windows"

    [[libLLVM.download]]
    sha256 = "f0066290071ce67eae3fa1bc41c0aaa0aa979e9525072aa87f82ec7bb30e9fb2"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c66bae69a9ea11b230a96af3e5f55474b7cf5c95"
os = "windows"

    [[libLLVM.download]]
    sha256 = "01e447700e6eae4786cabe3aec2d003ca0593ad28038845a282eaf6c96d7b65a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e1849fac172fad875a2f285964154bd8ab54559c"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "c9e20df2fc23e1716cd5145c280284f71ee674e82cae31960069b8ef0766aba3"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b5ea2bc18a4841ecb1e25eaffbdc897e949f8cd"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "3b86c2e499de19f238421b21ed87b73723338836f9c3e3b2fb60f357036ad242"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "01c4bd28b96256ebdaa3b4a43de74f675bf81b34"
os = "macos"

    [[libLLVM.download]]
    sha256 = "dd706283963aef411bb0265c511358fd98f7ca8f5ebcf1d33dfa3d20f6992e3f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.x86_64-apple-darwin.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9c8ea3cce50df7b97d877eb6e64074275c6b749"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "eb94961a38f4f7edadfdb045e4cf24c02274d7847d571bfa15190308705fd3b5"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0cdea0827cd5a34e89d11a338fda8ed2af7c34f"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "85d7ae8a644100bca3da25770de96f5e145f6c2b2fb20546376e082e9470b318"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6099567f08396a1e13db3a60b6e2d16a0d4dcc3d"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "edb611b3ac99c6e5739636be518a61f89cc2f14bd1d3f3726feb104cf649191c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "668727d8a5d9e5e76f4e69275eb0d87750a89e13"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "4151c2c334e8280b335b24cd60dc5a84c7ddfcf70aee0d58054c27c9fa66243b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "58050cf66bc967cf8eecaba265b7e53c3b7f80ea"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "ed1cff60ca568ec619a5260f3b738bace1cf01baa454cb721f11298614e2adb2"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ffa5b1e707f38c8374b02aa9377edb101d6e65a9"
os = "windows"

    [[libLLVM.download]]
    sha256 = "1d7164a42f48f628ed5724e50987c93f0cdd2fac093ab9d53fa2cb5589e6a832"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5199aac383abe548f1fc6ed960b323cdce44aa0e"
os = "windows"

    [[libLLVM.download]]
    sha256 = "8f35a4036e3f06f048d493a418c1711ad06606b1da27c54a4bd9d80b47c37b55"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+3/libLLVM.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
