[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3469cd0e6028021b58a41dfcdfaa559f8a407c77"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "36e9bd21c5745d0fc2c8600065ff1d6d742d56d27b2c5b112bdd29667d5d5759"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.i686-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28c9985b4b2aaa10a81ba40b4f534603a080e1da"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "07883fd1de391569be2d5021c5ff5cc753b29fbb4a7346103a248e153ce5264a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "26c6546fe24d6c4ebcccc609fbc480ec4ff17ea0"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "ca27b3ad19c772c7c457d771575db722a950e4fffb4589ce77a946dd282a747b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.i686-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2e8d64fbea33cebdc8ceadbccd283bd66aaca6e"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "fcaf22e3c3eb61cb860e718437758d0f991db52e7c7767d1058ef9f79ea17087"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61a69e0a8313531df8b7610d45f2bb9c3c56c88c"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "3625b0f936d0a1ceb3da455dd566b834c8f6d94edf03d0955ede02518e9e184d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b992500944d78f0870a2c3c97650e064b071272"
os = "macos"

    [[libLLVM.download]]
    sha256 = "c74d100a021a567b3eeb54f960822be08a4c5c729eb85e413ff34302c9e5a2dc"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "79147d6953379346c64c2d158eb443989a2a1b45"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "b814a3c3471c3fdb13b5aa9b27562899f501bc9e5eedb2928d7665024fa8dc7d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "294a8eb75066d68d782c4e02fb1344a9c0e45f6d"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "a42b29e130b0bf7782736d64c36c5f9d2a757d6f4e7fd28b77183adb819b6a13"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c66b06210c052c43131f938df5871334fe146ec5"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "947b2bd3e04c68c72cc6c3b6fe3a7e0bac849244d2339f122eba91a44971cfe2"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c746e782d1f1d5750446e7bc2f51a4ec0cdcd63d"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "18ccb9fcd07d0ab7fe9b049cc8071acdcec3903e6e17868c4a05fdcddec09c99"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.arm-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5bbf110d28b3937b47d1d23c1e651a4b09e2da2c"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "4890632940f59c561f9cc9449836f6be417acd90bf2cdf3e70db8805db59e702"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee96c650accbea1f50d8c14e0c4934dc1d06beba"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "ba861adb419db7c3860086d18cbae5795caa5d6a3bcaa0b0b9b89fb9ae13acdc"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1d282c11d4de46bfb043a2f3ba8825d83bad21b"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "54cb396b01bd5d9fcc98cac773b44f8cab731225e3c479d6be023394e6206621"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.arm-linux-musleabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b992500944d78f0870a2c3c97650e064b071272"
os = "macos"

    [[libLLVM.download]]
    sha256 = "1b08c43e067e67ccee7c9c9be0bab9623ff6df04d474e24baf931acfa336e92a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "92c227ae18858dc4d3c242feca9b170f015ac1b8"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "185e6c7147ba50b7fbbc788b1eb856b8262cc9917ff739576fb25e2a87cc13da"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e18c3ddeaae07b8669ef9764fb6560287ec8e987"
os = "windows"

    [[libLLVM.download]]
    sha256 = "950548ddc5e601c18480ef934ffc1768ac9b3d2813f53ec6675b9cff73c1763c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a7e1e48800226234578183574868942d9ebafa2"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "d8faef93dc1bb4e31f3b6476afe4d9ad177eb9b0f3f0f7a4a0ab09f1dd338c61"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.arm-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca5baabf4b0efa0bf9e38d30c302b563b257acc9"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "82a948796fde55808dc3131e9782f522fd7c441065fde78909f6bd375a3fe7f1"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c39b27744ba5bf1fde09cfdf6c60f9dde8bdc504"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "a9727f25352e3e22339bcdbfeb95a4b9272508f6a2bcc00d4c32a0981a55cc2f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17b8f68fafa31553d45e60ab48aa9298dafdda4b"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "42a5ab170c31d4e19c0788626504239cf0a423de417baacb46ae9da54a69cbbd"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.arm-linux-musleabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5db2149951eb800fed1f39b4e54f15493d1af15"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "421cb2dab85f010dd5f5a7d0c1a09c1aec73fb2733e1b2b28720f13459992333"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd11a0506d6042c0c7f357fe32b74a849a529cf5"
os = "windows"

    [[libLLVM.download]]
    sha256 = "f92af2e070b141fc9eab6861ca11b145b9feda55a9fc9387bbd2d5450b0a4899"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2de7bfd998435e0c99e2cda2952c3046f0aec6e4"
os = "windows"

    [[libLLVM.download]]
    sha256 = "7582af1ebb6423610973049ddbe2378fd4e069d5e917d6bad20a943e46260abc"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef5eca91c980448c8dadcefc91d5f1b8099d7991"
os = "windows"

    [[libLLVM.download]]
    sha256 = "121f6893043940c67c83281f18893f73bb91e24eedceab3bb37e25f2837991cd"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5e8cbfc8f95a6ddf032bf521518ab9095b1419d"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "75cbfe95d05797c3713984146ddedd4e2b657cd73aa5d679f8cbedc23bccb61a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79147d6953379346c64c2d158eb443989a2a1b45"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "d81af7326da25037f750bbae5e192b02c55181d6cf48ecb8117f5efc4359774f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+0/libLLVM.v9.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
