[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "bb346076e1f77cb89420a1f2d6d22154500ff51f"
os = "macos"

    [[libLLVM.download]]
    sha256 = "bb09c5a5be8adb85f722f24da21f839fedb1a2b9a40a4dc3270f10992a1acf0a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.aarch64-apple-darwin.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8c0622dbb578f2c858ea2848353b40ab2596765f"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "5d55241bcae589d711e0db89852ed32f1b7fc66799a4480234368c2997c65c8d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c5ac2c79faa6b76600d941033f1a82772242e60"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "1165b4d9d2d0b1c08a472c90531378f4539a920dc80f11e9c7c029566afe6409"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4818e20d8f84073e1a01f18d2a13a686cbf6ab45"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "4c20ec9892a50387408d36605fa5e078639e7389d468e2086092e1d70acd083c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44e1241c566fda31a90700f9bf50d21d68350533"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "3b44da120dc6b2dff62a7b15d72783905b2ad4c4ec7d39862140c52610577c83"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef4ced2d2d8d46052a9f4b3afde6a0fe653ba75f"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "6b3ff1dec3da497d34020682bad46de00f5c6d9aa9273f08dc40997af4410f27"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88482ea59984ab7cc22557d89fdf8dfb74f33a32"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "d1b1dba85478a6cb9ffe49d2c1f0c6e8274f74177359e0c784b65ca1d26b1eb4"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0f77642838cf38d22f0b2377d366765d2b8d89f4"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "75b1affa1d93f61908c987b9cf9678a02c46b29d9ca52fd5e8f5056185b26b09"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06c80aaf40505b212c33cc49837f15107b262ec0"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "3f6bcf6f3bdefebb0a7bf00a104489c4775b8fec0680cef577116a76d5651e25"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc9186edb5b71f7155f7e16bf3ef027becd0e394"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "3c18586e3c970d9496221b909eca8eb2d60f9c34abe636709c6bdba3a25e35b9"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc36dd138868b7eda3f3b3f936c4cd0b3da5ffbf"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "ceee75c9f663361f5181aa2d426cf46228651c08b92404d9b0ed933ad38746ad"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a0d19801c6e071daeb2a31203f2482e3f34d2ea"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "aebce4b80791aa45263823b68a71bf20d3d17e0e425f217f0f4ea99f42f35c1f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e62a869861bde4d8e0bc82a1a900c6a45f687b4"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "55a158a5a17524ba58833002dc15b73c780354a0a2f039e49fe84441c3c585db"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d06025b9f0d22e3ceb81446402658da490b41c22"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "f3402cbe5d02574cb224fe30e7f64b75e8d280c09de5326f3467b6285cecf534"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43f8fbf9d11bf5e795a7d2ac94918bc537f5b48d"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "ab609d4329604defd8f0410b0fce66ea2a9930b0ad6a924e280efb7ae7134fd0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb7f38f77bad1c51326b7a910c62f510332d19b5"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "eaaa875b665db6b6f6f3c2a1167a50ea209d70f763b3eb6bdb278b18bbcbbb3f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7532ac536b8ffa1b3edfa7bfd3d2cae0eab657e"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "08b8c263225a68da2c5c673c8d5f7c24d63e92981ed8e10b818f598bf08a2e88"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cdc00a382365a6fd5ba8b8401985ef481cea07ba"
os = "windows"

    [[libLLVM.download]]
    sha256 = "ae4d787dc0cba800a2af64ebf2ebbc5a19380f1c6bca05d6b1b9ba5160db1594"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a668baec6bc6131500bd8e4b6c1aaa72cc9616da"
os = "windows"

    [[libLLVM.download]]
    sha256 = "e49f663847d05483af02da07f8c518cc1d7cb743880ba76b8303dac261e89d69"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "add6685343f6373b6c9740deb8f990de1c30a4c1"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "7e4fffbb192dbaed5468dd9e2bc878b0436795eb41d20c33418587c606bbca1c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bec18f9fda8979d5dd6bf5174f7ee838bd1bda1f"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "51f6a95479f212674846a2f90b9a6802ebe34b08442ca5f0e480dfca83ec99f9"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "605dc73f45cf0371a0257855c8973bd8829605ae"
os = "macos"

    [[libLLVM.download]]
    sha256 = "6008b1615705bf4a1376c1c5bfab34b19439ed6ef9bbfb87725f15c027d31a3b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.x86_64-apple-darwin.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d9353cc70728ef76d57afa65eb613cc1d0cbd9a"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "a928a78615d7fcc10a4ee4ee4edeb2a31be2535a76bbe70274b14b3b0aa3da87"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f429e3ab9f1fee25abdcd61892be6599c57343c4"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "7be12a3d86efef11ad543527d424258e010b687d57f82a6d8bfdc07dfee5d0e0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "552bd0f4b664b7fa4074dd883285c6131c3d4de6"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "ddad65e5a1d0abe54a30b67cf2c03ca7ac26e39ac124aa3d29c1dbd5ea6472b9"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "539d5cc30c991f0c15accce7d73638938f8057ec"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "2777dd85f03b78015c445ec4ec7fcd40297bb40bf3467544e10b8c37579f6095"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "ec3614ba2a390e317d851d642798c67ca059d401"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "0bc7918e67298347f9d4dfcf5e8e0b4c8e1f9144d2f21bba46538b59befbd8ed"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "baf2f61a1281c08714b2808f182d97120e2c2c40"
os = "windows"

    [[libLLVM.download]]
    sha256 = "2032565abb115a7eef14aca29b30130c2e4eea4c746d0178f35314f7fcc29247"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f08e9275d6df0c2282bf38020b1e81796456eb6e"
os = "windows"

    [[libLLVM.download]]
    sha256 = "7d948fe9ca41c19c58946e54c4b7d00d40ead65583efc30dc9544cd73bf2eddd"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v12.0.1+4/libLLVM.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
