[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "bd50cd42c5af61d75ad83b3ee0c3861dfd06a8da"
os = "macos"

    [[libLLVM.download]]
    sha256 = "7b4bbb6f8fa9c9e74a02d3139acfb8f2f75dbdde28383ae5f63e7855328b633b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.aarch64-apple-darwin.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f30124a1cb0d337785d2a57600af9085abc9d965"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "342b7647f5aae59a6dc6d25983c66a1f08da6f406c44a752f40cc3a0d2545b31"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fcb13b8a5681916a05a49d29df1acfc5e01cc402"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "3dc17b01cfd86656b74bcaac0c7a8a06cf0f437a314b75871c4a314c531d3f26"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5aca48e8652ad873e0563ba4bc6ec866b6f416ef"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "3bde3eea4f06f2bc75061ab84d609ed9bef9ffff74d63ccd3a3725283eb08885"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a58d5f63b9547d91d6de4826dcbd5321f6cc63cd"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "6853da93e925c054cf3af9938ca04acef9fcc3bfe80297d331fc64995c7b3a32"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "090ebc2b88eded783b675aab7751c7932edd8ce8"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "7feda1f6412ba5a6659b64626aeb4ad81832c3128b69dcc16defea0b61258054"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "862f257e4204b19318324dbbf3d19ef63c1eb24f"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "62af20b55e88025f8a06f108806cc38091102b64e106a84b0fa164db775101e9"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c2730339cae3ab8213f627a20c0b92ff6c08e63"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "189d4f196119f2acd2a2dc75122e9a4fc5e452061861614b6feb89e8e4dc6aac"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "90813954a99bd29151f713df4f9e174982127dba"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "ed44f89fe7f653c973218159b0a2b2c010ca6f2bcfe3d3605dbb6e44fc7f9124"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cab1beba526577c1312e716b1dbf41f8b80a0c66"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "b618e7e80fedbf86a0ae41855d513c5a201e48cd03842724193a0447b7a788e8"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1d2ea921c6712d493a16a5d9dc3aed207a5fcbd"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "866953b8ba6f7ddc0fb9a2e1404a1a590ff36c6580326bd1009b7b6feef8a98c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "06b08283e093e12c7ba8dfa692dd4872953701d0"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "0882416e19cab09a2e7150c117ebdd53403dc7a47cf878d4b7842ccddf824473"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "936421c588cf470ac21b48a865ba1ec399ca5594"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "bfdeeca8124285c9ee57e250d2808129f67c1c60779f1fafcaaa19a2d983ae19"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "989392f78805fb7bf7441e6b35a67c54091c960d"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "272ba39b097411c81c6c5579b64930b852507566ec882958df2b6437d1f6907d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7e87052f299102ab5127e3e4be29680852791e4"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "9a4e37176d0f1bd09791df2ed897f503963589360c1e8588d0ce6de20d228fe5"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5c973d5c92e14df39745cd2a034c99a6a993bf5"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "8df3db379d5641783c8c21a5d5b514ccdffafa2ccf2b2c71016caacdbc3311e5"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.i686-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00fa4ed2d270cdf7c6fe61820a0eeb9ba084bfb3"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "fc814fe4dcc4ab4cb16177a6e51bf75a02c26630df7a463a45bf6a6798f39e43"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.i686-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b9dc7673a839ca4cf1f45a9303ffa46d97e49ce"
os = "windows"

    [[libLLVM.download]]
    sha256 = "27df7ff5a7de8d7229733f82a482d2edd1317aad383c480bd600d5c1eee0c3e3"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6fab8d9fe5fac4b2f7dc000f5b51c1b4fa47542"
os = "windows"

    [[libLLVM.download]]
    sha256 = "24e6fd03181097179728e7eb213bedfbf83b6e0a46ceaeb6e70733eac426c234"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e9afecbfdb8806853ccae4aa49f3bf1afb51203"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "15cf41342b5e858bbf520523714b6d2b9d12b18abf588765ebd88793eb7a041a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e38243cd3b684b231ea707030b7cb2b363df476"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "d6cce2d8cbf6fff0daa4f3e6f8bef752dd0ba9fb45f4d89f5803807fa49d8293"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "87a327b25004f162925379954f558d2ed126a531"
os = "macos"

    [[libLLVM.download]]
    sha256 = "219e67dbb21cac659fcc87dcfd2da51721261e3cf9bd6816cc2c2c98650e06a5"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.x86_64-apple-darwin.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3a2b41dc84ea4d87a6dbb84d625fa755166f347"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "411f9c4def4989fa94e3653e147db010e4481d1eec0c46a76f55f167a2ed4b69"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85918ec1661a1c59681d78f81716c4e968881c67"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "462402857721c7532b7f1273291476b9992ab1693c3b1cd09f36ab466f6deed0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85a6ab4f38c688168f338e6223b06cb9b5c694ae"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "9b0d3df2efd23b396743a519c619b7e2187bccb8744dfea9bfe8ccc1d2e6a4c1"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23a3f394ef32c51c7315bde5704fa3e6f8c83d9f"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "f4ebe94f81b8c503a940a99ca690cf6b93c22e01620dd8be601768e8e4f6fd85"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "a8ae735c93f3be5a15355b32f1e2dd44361cfeae"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "d4ae5376891867415b0c175c75f16262d423bb8359ea166de9d1dce785dcf4c5"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.x86_64-unknown-freebsd.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd1311f66b6e9f32084329af30bd753934e56afc"
os = "windows"

    [[libLLVM.download]]
    sha256 = "0df8dc00a4c8317daeba8b47fcf024d361b9df108719c7206cedc14ebb9db7ca"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "871d9c1d25e8e5d33a7a492bf43caa70f0dfd6f8"
os = "windows"

    [[libLLVM.download]]
    sha256 = "511fa9845d8d357f17e2d32b3e3817a2a15bdd5e6d0fcf7cf84978bbf7d836f4"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.0+2/libLLVM.v13.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
