[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "a8126b48dfece09e4aa5ffb61e6b97045e946536"
llvm_version = "20"
os = "macos"

    [[libLLVM.download]]
    sha256 = "9f32ba9cb3490d4f61c3c40d1d3cb05bbf813d1214ee179095bfab3c2254e4b3"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.aarch64-apple-darwin-llvm_version+20.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c06d3e9b0d0816ad9b6e9391700c44ed4d5682d"
libc = "glibc"
llvm_version = "20"
os = "linux"

    [[libLLVM.download]]
    sha256 = "d1914142ca42d0b1d4cf44270c6b53cbccb6abb051cdbd75c45ae83a2d24a727"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.aarch64-linux-gnu-cxx11-llvm_version+20.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e442c66dae3fce34dd9106c20c790c12d185e096"
libc = "musl"
llvm_version = "20"
os = "linux"

    [[libLLVM.download]]
    sha256 = "f6decd6928b1ec29146c5c5b334aafd646684b2bec68edbad375f973a9513035"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.aarch64-linux-musl-cxx11-llvm_version+20.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "8fe6f431ed7e972afd418c8022100f60fbb78690"
llvm_version = "20"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "507092552d55181ba5ea9dce37c26af6ac210a69edd8d55c42f71058ff621c12"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.aarch64-unknown-freebsd-llvm_version+20.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed63579637bd76e79b1721c310ba4a54da02ed25"
libc = "glibc"
llvm_version = "20"
os = "linux"

    [[libLLVM.download]]
    sha256 = "5aef8168fe0b8f8f4d6dae498a49e38252797abe3e4f97040d19fac98b316972"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.armv6l-linux-gnueabihf-cxx11-llvm_version+20.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9510473715020dfaf0e0303eebcac507fe20a98c"
libc = "musl"
llvm_version = "20"
os = "linux"

    [[libLLVM.download]]
    sha256 = "8f4c324f3d6da9f0e58eb2f4360bc90b63976d737fff208928b76444f45f7b36"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.armv6l-linux-musleabihf-cxx11-llvm_version+20.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b9f5ef90848abfac8dbb3766b6a916725def228"
libc = "glibc"
llvm_version = "20"
os = "linux"

    [[libLLVM.download]]
    sha256 = "5976abf43e188f27354a2e70c68fb2f590b591a4eee3969e2ffa7a8fb5ab5dec"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.armv7l-linux-gnueabihf-cxx11-llvm_version+20.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e6fa4026813592abe6b7ed00f14ee2ad753ad92"
libc = "musl"
llvm_version = "20"
os = "linux"

    [[libLLVM.download]]
    sha256 = "658892ae2ede8d595719f2e26ec6ec88ce12416f65c6d8b0e803a27a5ee9f21e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.armv7l-linux-musleabihf-cxx11-llvm_version+20.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74d8d87ac59aa24aff7da6debc0bef644706b24e"
libc = "glibc"
llvm_version = "20"
os = "linux"

    [[libLLVM.download]]
    sha256 = "406091e5133899c5d6bd5803922a7763ffd5b78838d258b67e61eef2cdd4a3ed"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.i686-linux-gnu-cxx11-llvm_version+20.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d1f3014ae2c6e0fda759135c92f5e58799648f92"
llvm_version = "20"
os = "windows"

    [[libLLVM.download]]
    sha256 = "b9dfea30bf2e6259607fc93ba2766cab3046e3417a24e0f6c280fdfefe988e1f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.i686-w64-mingw32-cxx11-llvm_version+20.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10444e4e13a6fdc23686f4460dc4154c8057e1a9"
libc = "glibc"
llvm_version = "20"
os = "linux"

    [[libLLVM.download]]
    sha256 = "664651f33ba28f81a64928721b1dc91ba2796bffba22e9b17ba776fdec3c2cf9"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.powerpc64le-linux-gnu-cxx11-llvm_version+20.tar.gz"
[[libLLVM]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8f227a9038884dc8fa69bb30958496fde7d0e63"
libc = "glibc"
llvm_version = "20"
os = "linux"

    [[libLLVM.download]]
    sha256 = "e3e5db27e845f7569c71d2671c510843a27782a2f0ee2e9571b815633c5f4e98"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.riscv64-linux-gnu-cxx11-llvm_version+20.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "acdb0578145578588a1ede1ed065632c9f0ceaac"
llvm_version = "20"
os = "macos"

    [[libLLVM.download]]
    sha256 = "ce62fe0cc9fc526489405f60ab4e28069a8c98ccad2b915026a81fc68d93ffdb"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.x86_64-apple-darwin-llvm_version+20.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "137c0f1dfb6fd9e801c5c7166d3130a4f85847d8"
libc = "glibc"
llvm_version = "20"
os = "linux"

    [[libLLVM.download]]
    sha256 = "7fbae13f564f99afb9f8cc9ce8f95631f2eebf5f8bc84a225d4c441d7e245131"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.x86_64-linux-gnu-cxx11-llvm_version+20.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "137c0f1dfb6fd9e801c5c7166d3130a4f85847d8"
libc = "glibc"
llvm_version = "20"
os = "linux"
sanitize = "memory"

    [[libLLVM.download]]
    sha256 = "7fbae13f564f99afb9f8cc9ce8f95631f2eebf5f8bc84a225d4c441d7e245131"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+20.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9cc9828a92a66858a60c633c5b36e20f47617e6"
libc = "musl"
llvm_version = "20"
os = "linux"

    [[libLLVM.download]]
    sha256 = "a660e85255a602abe9d488fa31f62332f90ce039f82932250d2967e0c784ee8b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.x86_64-linux-musl-cxx11-llvm_version+20.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "420c8b571c64f1ab9239d1f15b5ffa7bb630b55c"
llvm_version = "20"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "c156f970a7924e40faec54e9c405c1ec6f6d2652ad3ff6ef13773fda1b78177f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.x86_64-unknown-freebsd-llvm_version+20.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "deec0f6edf5af4ce8d59e0b941b04a33c1cb14c7"
llvm_version = "20"
os = "windows"

    [[libLLVM.download]]
    sha256 = "815e580243ee97e5a02a5f775b3c7c64073905652566d47d10c6f7d2b9732d59"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.x86_64-w64-mingw32-cxx11-llvm_version+20.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "14c0ddf1e1930c7016d5441488c31f929b872e5b"
llvm_version = "20.asserts"
os = "macos"

    [[libLLVM.download]]
    sha256 = "fccc74bca20be5fa89ca1883354c344b8e90296178b9c9b5452b7e7b2a3aacd3"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.aarch64-apple-darwin-llvm_version+20.asserts.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a317feab76d74ea9c8a0d94c50d15d29816887f"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "e20d5a5506cc6011708bf3f0cb174a001ed1e775da4b6b5484d8316324d052ce"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.aarch64-linux-gnu-cxx11-llvm_version+20.asserts.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f38dbe0d25f79d35af921d7e56ea3ebbe42a991"
libc = "musl"
llvm_version = "20.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "863dcd550e6bbfff6c43dcd9b8410e730748f7759d8f5f69b8b19cde4779ef80"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.aarch64-linux-musl-cxx11-llvm_version+20.asserts.tar.gz"
[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "4d66888f02b34a5a266fa9522f526d4935aa1922"
llvm_version = "20.asserts"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "8b65f4112456ee7a9b84f7f98b80020282e6795a23f0815d05e51a022f3304f0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.aarch64-unknown-freebsd-llvm_version+20.asserts.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4ff61038723f9c9efc9aef2b1363ff9db2df9b1"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "37bf6b0b37c591253787c2fec8d5da5bef6af6a747daef0d4329720080a6f212"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.armv6l-linux-gnueabihf-cxx11-llvm_version+20.asserts.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "34439607f324263034e68c49309f3f788d51d7f6"
libc = "musl"
llvm_version = "20.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "16629f865eccc9ee1d8a6e73a98e2758730ab7d9591a265cc0830dbc35c1fb2b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.armv6l-linux-musleabihf-cxx11-llvm_version+20.asserts.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b0c161d7487c7d11a398ec1efaf6742ce4a9930"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "747deb6d1a076e423d3050c14bc8372d6cc7665f2e967ae0e39e2a1aedf1cfef"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.armv7l-linux-gnueabihf-cxx11-llvm_version+20.asserts.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "719e91bceed45c5a6c2a7526662cc066d398686d"
libc = "musl"
llvm_version = "20.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "0f5d8055ccdaeffd0242f6fc9f8044389216dc1175dd7e0a33a1805d0f5c5e47"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.armv7l-linux-musleabihf-cxx11-llvm_version+20.asserts.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47d47d06398a5395353824c559029fa912236072"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "9f5e080654eb058e5606b03a9bf6165684124c298f6f02fd5c2e42718a78b239"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.i686-linux-gnu-cxx11-llvm_version+20.asserts.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37ffecb6c244be643ccf660a7f1d84174c345895"
llvm_version = "20.asserts"
os = "windows"

    [[libLLVM.download]]
    sha256 = "ad80dee7358c5681e8a3298d297ae4e8a16d0b313ab8cb0784dc7f0b2395e61d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.i686-w64-mingw32-cxx11-llvm_version+20.asserts.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21ebe1bf325403d4fdca1ff2b2253ec70e91667e"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "9df9acf5f2807709e84a4b71c20a048ba5bd916aecabf722e70d001337afc9c8"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.powerpc64le-linux-gnu-cxx11-llvm_version+20.asserts.tar.gz"
[[libLLVM]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63753c22caa9102a074b4e030cad186ddca6c7c2"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "2186515598b06e70211e5e87aa4c6aca35668a16a45d631a29c083475a662d31"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.riscv64-linux-gnu-cxx11-llvm_version+20.asserts.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "edeec456cdde58b3671c0c2700452cd884176b0a"
llvm_version = "20.asserts"
os = "macos"

    [[libLLVM.download]]
    sha256 = "886c57a9f657acf10f855498062a412947d9d00f976c5f5e3bec9585b051f21b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.x86_64-apple-darwin-llvm_version+20.asserts.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c63b2ee04d67d951fc0e27d6b581301b266904c"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "da934f7f9cadc20771d174ad9876b0e63137dad17738240754fa5c0c2f7bad4c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.x86_64-linux-gnu-cxx11-llvm_version+20.asserts.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c63b2ee04d67d951fc0e27d6b581301b266904c"
libc = "glibc"
llvm_version = "20.asserts"
os = "linux"
sanitize = "memory"

    [[libLLVM.download]]
    sha256 = "da934f7f9cadc20771d174ad9876b0e63137dad17738240754fa5c0c2f7bad4c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+20.asserts.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c09efb0a524b5a5430684f3f12c391ea46310b05"
libc = "musl"
llvm_version = "20.asserts"
os = "linux"

    [[libLLVM.download]]
    sha256 = "8e84669c4142b409649e7a88276877fd23ec5c946b254607adc0067897de031b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.x86_64-linux-musl-cxx11-llvm_version+20.asserts.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "1e49d01a66eac56bd78a9a90ca39bdf1f661d0b7"
llvm_version = "20.asserts"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "b6e105c0c054cc07d3d65f66b4d77e0b4a4bcca4fce95a19d63e69030a79eb77"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.x86_64-unknown-freebsd-llvm_version+20.asserts.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4eeaea92f7b57c5223d18541efc2e61a8391f11b"
llvm_version = "20.asserts"
os = "windows"

    [[libLLVM.download]]
    sha256 = "96927725ead1f0dc184b285a7c504c788e641e3fa8bc8a12d95768ef69a9a178"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v20.1.8+2/libLLVM.v20.1.8.x86_64-w64-mingw32-cxx11-llvm_version+20.asserts.tar.gz"
