[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c623f94966baed1638c5a5ad75bd59f068e7cf36"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "d4aebafac27dc6f5128512bbd46cc8293b7b922d08d08f0dc0f1a728615dc603"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e24b809af68a243a53278f406dd0e84ae4aa60f4"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "5b0f36aba3cdc14723bf731bc76f591e49d8a816e8ec6f3ce33edb067100feb3"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ad5b96b88a5114d2583e8658da8927cc8fdaa3a"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "ca446e927c6cad6851ee3dc2d76255cf317fc3c6b1854aaa485c14dfe273b155"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a0c9a20a8564bcd9029fa740be2f4ff4b3533d5"
os = "windows"

    [[libLLVM.download]]
    sha256 = "32274abdbb418533369d0ab06813eb6deae88493cb0334b4f805285651da9c03"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c37a13b1b779c972bad307c8558504111100e59c"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "1ebd0f494050a5fd42a523fb479803ae4f87710bcccbc4c27be844cf7ce23840"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.i686-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1b88ae047835a5ec6f3d2790f8b5f9eb784f6ade"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "9e06a399d85b88e9dec5b12d9c8be1c8c2268be86f2c7f48642ac5520166b364"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "163e3c05cfc161874f2597e15aa97cc0112de5ba"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "aed47de7e75c1554b86ca013671c822ce72ffe012eed71dd2ce221476a8f95a0"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8837ebc92c956a8ab0a02eb81b8039461f05ab98"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "6402658dcf7c0284ef4d44016cea1f9e63c6bca1dbd07c71a0fa9c38c32d00db"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc7741d581fca7dfbc474f5a9203ae8d83fe9542"
os = "macos"

    [[libLLVM.download]]
    sha256 = "fdfeaf0379b3fea7d0851313de2c3a2592a03e084addcc1113148d16a95005f7"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef6e37bdf5f3d66d65b9255b50ec499205f1a1d1"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "1f05fc57a4ded60395f71387235f1aa02141a8e5cce2786465ab687386f7c71c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3fcf9ead5a7898631d8cfd22d13d2f09c8e0ec57"
os = "windows"

    [[libLLVM.download]]
    sha256 = "16017708819cf60b72e84cc06f72cd70e396d493e86ab465d1c5fc32729e4c93"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7cc9a503445266d0ef3aa864acee71bb5cadcc74"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "72854d8e2ed6db0e3634c01fd30d7a87e4c40733e312cd8cd3be062d95abfc6c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf6b9508eb148230f978dbdb72a3948afe0e514f"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "ad90d049c8a3f0f134d2d9f9633ab00ffc1b69c25a507a16b58cdc67809a7c12"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e8e1d8f55cae16ae8e55d0f0ce24755faab4f6f"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "1f4128e1d3d15bc1f5605785a4c8229a6929d2182090ad69289b8b63800e0c11"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a16c5000610ed8299ecc7aaa8d6badb8997e024"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "979e1f8349cfc3a9f25fec9672844dd272746bbafd16d68d43d19dfc9ad0c03f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc7741d581fca7dfbc474f5a9203ae8d83fe9542"
os = "macos"

    [[libLLVM.download]]
    sha256 = "fa610e3011ddd599b85e5ad7940afd6d4417088ea40a1bbf1838c92ba2279c4f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1a796205b7f28a63de0aa1bb61d3b2a8fb8f36b1"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "f85661000601607d294e145b61bd4c215a3eb792f43637334eafca313f8eb319"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ccacef7455cbc780372c8f266f52a68eed0253a6"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "d7bc715b731ba96c9252a4d887a37c9ea92c5eb4ec3fe431d2f7393911e316a1"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a4c18bcd23a978444aeb9668c601b2cb63b6716"
os = "windows"

    [[libLLVM.download]]
    sha256 = "334ecfcce778268098fcd704140d8931bf42c05033b773d678670dee8b426bae"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c4c3f79b2cad33cdac77f17dfd4800fd1123cbd"
os = "windows"

    [[libLLVM.download]]
    sha256 = "9de5d4592fe9f0fb64d3e676614345072b1a33be7c52dae83c10e2db42c9d0f1"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a12a97a770e68bbfa2b40ba18957d92381569093"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "c1ba0ee4b5995d31e0dccec288b6c835e50f3a191805b3e3a38dd94eca006c05"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "488b0c572c23a8fc7255872493e7a42676c710e3"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "70a0890f905960453982bc46f0edf8d1081613e2c644da3ea000568b96fc666e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce3ef901ee3de4c77daefe6826cc3d7a8be6b969"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "612c8f1e8345e8fc0bd0a348854485e23f015e75b689f3b3349828b0342d97d5"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3732e949223fcb11a400fd85727c6a23339c0a7d"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "663ff34102a0fe0d81cfaec698bb2397d6229f9c36a8ed18ff102165bbc8899d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "550dfd6e2633250ab5637f8768fa7e08d4244c13"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "5f9cf31ba83a5adecde8efd2db739f53bcf8b1a667008d6662074ac85edba079"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3fe7f65afae287754dc0691a1443a6611be44a23"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "4c4b7279307170027f2497302900b7c94365b0c760f30415a468a8225c7e251e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+4/libLLVM.v9.0.1.i686-linux-musl-cxx03.tar.gz"
