[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "cfa0aa4aff9635b03b3f02762a69e2987b24a3c5"
os = "macos"

    [[libLLVM.download]]
    sha256 = "69b08184ba5f4ded4d465c18a29c4f757020acada4c03713d7c5923c577d7e29"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.aarch64-apple-darwin.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c2d0ec1bb5ac262179440a6ae5c9bf921843083"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "666fa70862c6aae03c7af8a7c70cf5079d6d3c58bd93e781b4bb943268fa560d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "431ee2aaa8e588cd8799c1e5d96dabaed781b422"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "830ef29d328b355718e06ca72c691561a7f5d3e87a5368c4d6bae42962509d42"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "19081d8e8e2a904817cc3c5118267f664ab5e41a"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "bcd2274f04342399290848d25d8b7afe2c70a5649df8d915a53996cd17daa471"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ea8376b9122b351a47cd7103c4f637090a6b6e3"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "ca07c5a200b6a0d85007bb18b59c7ec39da30664387467139a8a69238a709201"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1cc50041c28d226c71d8df68f1b195155cdbce45"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "1f153ece3d1d28189cc59f98596d795283a81237ca40cb973e64472b24f4cad3"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f9ee530cae7ce6cd4c913910d7a7a4bca6c6aab"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "8fd43c9f4a93579523b447fd027db363b4ed18326ca119163e018cdc27e9aa42"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6617f42ef2442eb0ae92f2ff1e52bb10fccfd097"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "18c77678cc6aeba00854c7bd713033aeae24a349bf45e07a139717b44322cd9c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c75c35b65dbec756e84acd82282fc9bcb1e57258"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "a2fb1bef28c686aeb66caa604b1d30216f3f9383f7dc8f40a0c887ff5144aea9"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72cc60c6724de8a9120f626dcd93a83905245e67"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "ff68e27af8eea58e87199ba6b52d6abfa3b6f4516ce1f22f7d92c65dbb3b362f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ed5eeed6f7de0f0f2902ffa011fcc3132d04b9f"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "d2aa8c5bf63bed67c33a60b3390c8399de5847ff4e0ab354e1464d039bf3bf38"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b5618dc81645d4e5316b4e98504c29b18d9a5c0"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "4854f42defccfe9b261022848c0c36f437fbdcd61254d290bf9204ee74f36c3e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f02bddb909f95c484c7af0f73b2b3ff501d81a9"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "20723be117732d64c49a0f7ddf6b60553da4daa3adb2b12d372f63f7863f0ccf"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2eebef05d39b22338c4188b2cfc5bd5db769a572"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "189a04aebcba6af74bd01c56577ceda435616e7720425a25d2a36f8cff5c915d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3dbce7e36db3425d977a4aec57b166ef0748a95"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "25cf0f0a7864699f0019589de346367713eae393dc0ad174965e0fb62d2ea1d3"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7c287301e21e86937a5f22d2076e651e59b7a899"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "99997594c0afa22f66fff60248896a9a796d88cc5fd6b59ac18b6688b92de2c9"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.i686-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d9402a0f3559089928cf41dd5c5809f000777bd"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "d1af3995b4c86f14d3d160055627b92bf34f6087f7aba8758ab2c3d65e5795c9"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.i686-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f35247b5ad52cf6b2f406b81098ba57cf29bf61f"
os = "windows"

    [[libLLVM.download]]
    sha256 = "721a741069e772b8255587fc927004b6a590fd81591b216ad2e34983e9538306"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2fa0bf9fbb789c03e288ade3d0bc82dfa8a142e2"
os = "windows"

    [[libLLVM.download]]
    sha256 = "396a975cc87d6942b0e3187862fca21b1d09f58fc6b1463ea1b4807f074ae8bc"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "028d1f9848b208165c27a2aec1be3967eb0a7ff5"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "fb50f924aede32ef72bfa3fd06eb3ab000104788d5cc03f25e802a3de749819a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "960147a86a483a3d6d47fcdd0549f1e33270b2d4"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "e52aa1612ed632f75a6e8af5da8f4d5f5ad1c19d0ca4d949d8bfeb0c5abee833"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "2db15e69869149716bd3c2632efe07b6a7833981"
os = "macos"

    [[libLLVM.download]]
    sha256 = "60fec98de6137eca314b413228bc7b4afdc8ee8623bcaab684b6ee9f7dd9eefb"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.x86_64-apple-darwin.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f979ece76433662b47c867dbae7f2e526eb5ab3"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "948c3e68fa2e27e2a4fbfd2034ba9c436f3e189cc8ec33736d74b847bef80b37"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "583ca9f2ed918403c24452b4df1aad9e0e887bbf"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "145ef8ab6f712429d8e70393f9b3d697824f4851fa1ee25ee30da015f1ab0c63"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94b7b95bd2c371366d7c01b4ee5baabd79c21392"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "e9e69eb61ff8f3997c9649f41aec72ba5ce7d63d80dcb5f04e46918b50ffc2ba"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06df524ba40af37a8cf42e20a9e123be72226ece"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "f1727a8d2b870d2fd7e95931d3ae4c904c0749944a418316f270b2452c245a35"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "615d51c032d950260d6c3232da402a828f504c33"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "77113d6a2a3e6a67924a0d8fa8e4b4d3965b1fb55b93b20f6b6c70746ed47d8f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.x86_64-unknown-freebsd.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84187504d0dfa81dee22c36329adef73646ae593"
os = "windows"

    [[libLLVM.download]]
    sha256 = "2e105fc08f41eaa7a6199d49905a67b14b437c2b5b4bbeb1a3d36dec30788b4f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ebee15dbaa5e11ec08acdf9f22e9649d7009079"
os = "windows"

    [[libLLVM.download]]
    sha256 = "8afc743050f53dba7501db1012d06e44c72a7d80d8896f1ac42a5fdadcfa438d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v11.0.1+1/libLLVM.v11.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
