[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a1fed77e1db58fc31e3e302794d6f985ece77575"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "af7ec19d0fd1a043c75f2ae3a36a0ef74fba056a0795884ccd02409c137766da"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e62b6af9f2cae6703ce1db67ba76dc4b3872fdcb"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "cc57a5dd1b0e23d500216e6acb88734113290de91dc03f25f00ec177fe3c370b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "003d4f2f8d264591bd54f69bbfb4c373786e6acd"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "e096d8fd320fe8401e37d338a81c5753ccafb19916b03f2fa4ca0e2ccedc892a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6831c89b92863caab179e930602c898670ae871e"
os = "windows"

    [[libLLVM.download]]
    sha256 = "7445d1dd552de95211fab52bb684df0f51a5c0a60ac597ca0071898539bd3298"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b3961077e36cb8d102b2964d5a832cf7e91f41b"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "01c4fa2740d9d4126f57b1b9e1934ef209688a24f1d95e353eab45d526609867"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.i686-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8190f07c7b86166605e62afbf3eb10c1c4706989"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "f982aa316820c539679e772b1b160538304f4959e32e09ff929c951fd3211f31"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d6d97897d4e8b6713c0d5d66ce3a89a8134000d5"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "aeb91a1736f76c1c2a85890ca89e9bc2ea12d543e4fd8576dd39b09cafa661ba"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c65e3e99deed3df2c6f385cbdbade591a58425d"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "9e4d9457a7b666f568226169e0f9bb67ca4569e6ecdc4efc8dbc9005bed79d1c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "406c3c69fd526bc1bc87b36fdcd9d31f626d9cb6"
os = "macos"

    [[libLLVM.download]]
    sha256 = "134c32f89eaa50157e67b44dfcc19c0a80f44a125bdff138d9d3693d25142133"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "17e0db92171029529ccbe8dff40c012e7438d85a"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "984a0c3542b8e9a040666183aecc763d6a5e2aabc4bf38054c8c1af908ccab08"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bdef0ab29c9e6590d98a89e184667c2b7e9f0b6e"
os = "windows"

    [[libLLVM.download]]
    sha256 = "8b70a0009ec6f98dfd3228d7687287e70ce2080a16590ce67894d7c82c3278a7"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b5cb0e70098fa2a1df9a10550ebd8e69b9cf3232"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "76eda229e552e79fb8e4629611c8877402a438b7b1bc25466b3c39e403cb474a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1817f0e1abdb7357e69f9d105c43f8405a3361e6"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "12626d11cb7ca9e4de8ad416722923c512dcb1028105754747f40c5d0503a4c1"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20d25c094d5c112bd90cd9a489424b1fb656c3e4"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "8ecdb7e94759e40aa22d715174af25f85f919c71505eff015474d833b5fe1ae9"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4c92d456787b79f66adcb51e3e63be7c097b0b1e"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "a9ff8f37c98fa4fdb40cf9e0da995faa068a63d9acd7d74fa102ca68c7b3fbcd"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "406c3c69fd526bc1bc87b36fdcd9d31f626d9cb6"
os = "macos"

    [[libLLVM.download]]
    sha256 = "82edd297fd08cd195225189b2377fbf98caa533ffd37a9b54c64857ac6586ccb"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "214ab572e139e4dd742fb8be6def4370e130f757"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "a5bd8c789805e7fb40b0cb8c2ac49e7a7f25b4db7b0c9093be252c80136ac805"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2fc6fe10b731ab14c0c9ad77499c5ef6cf83474"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "507553ed0bb424c575af7bde0d51bf5fbe72d1bffa5ca311af6e8eb984ae7091"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5fe88ebda0d93d69e59262ec0dec19302c21f3c4"
os = "windows"

    [[libLLVM.download]]
    sha256 = "c25b0df4b5ee1eeb7bdd0a50753a131dca754ec0b7cb60cc4abb1d010312ce2c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47b8d3424fca14b22b77eddc6495c482ebcbf6bd"
os = "windows"

    [[libLLVM.download]]
    sha256 = "6e005e9190eef7d9a7be8dd9b9593e81492b0c8700b87eaee1fdf3258db2aa11"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9c11ab85d0221c635ff44480109a78aebd37571"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "705ce1f32bacc91285dd348916e4a1a5a87381e74da521b5cc7a7941ceb50c88"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "56dc62b4708fbdd9042ed89bfc47cc4fb1d7ad54"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "23837d4788eb5df349e6df01dc76f43b6ad95f5b16b92738c821eca51ba2880d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d1f80ccdb5db5a7121cc8106612e5fa4b4dd376e"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "78f10b8a740547643f6322a568cf0e9be1e42b2fa9b99a9676f13e381fe749f9"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9b502b7e7095eb363fcfad00ba70648c2725f00"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "87289be8bb41f62abc2bc5f14631e5770437801ee918b104e1cd2da7297f327b"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2df3c4cea00d560085dbf358bd1104a7b2906948"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "9684e1aa27a17c38653d7032d299fe44ca1879ac2101ab15e99cf082f965ed7e"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80db66f5201abb32b2e9ecb72004c0f33bca70b1"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "c2eea4c7f0b7042cb7268be172166ba8e2602b8c7bfa4a7622afd7bca3d3115c"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v9.0.1+5/libLLVM.v9.0.1.i686-linux-musl-cxx03.tar.gz"
