[[libLLVM]]
arch = "aarch64"
git-tree-sha1 = "2c7a3cd6fcfef34e30f49496d95a7d764bd6fd54"
os = "macos"

    [[libLLVM.download]]
    sha256 = "4438918d45e90ed599f47912e2f0a6ed4721f9887bb89e2abf7de633637dd2f6"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.aarch64-apple-darwin.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f73f5095ae2f7b4c7da593b888857fcc5470dc87"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "8b1462a9812bdd5e921a8d789560f3c49785d569dd643c5ed8caef5941ce1eea"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "571a4bbae4fa3c03be8f15bd194376c890848f0c"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "db4c3a2b191a5d8780297b37f37101c3741dc9d6b82e91505f1a83cc76509636"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e79123228dfb9d563bc8d19309a4c322f8f6779"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "dcbb39c133d2e7c470a9633fda200753eed5530a18a544c263e2ad41ea1fac61"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06ac6c72dfe1fbd33480ecde33017cc89d6806a5"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "a5ad20c36ae081fe3285191b40aa460b8c638541901bc38655188eed3872378f"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1348fd3af8a37a71cb3f75a41be5996260e854c0"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "5a6a97a50474dacf85a5e9f1aabbed3f3dd8977063f63d476037fcf12078a789"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c83e5206fc3aeda9d3ce44c89e9bc1737a8f0650"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "620a7089890c914c6a4e4a0ea28a8e69cee7a3d8969a382d0af5566dd82cb7a5"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb76668547f64d2822730120b3ab97987c82ab1a"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "3b764fbc250bd8635894e576027acf221bd475069c0caee83c9c5e40bd484bb6"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e22946dbb98a85335b5b410993146f317323cddd"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "e0205228cc8093ad982d2c8c09a1a16dad40d6a91192ae85ba37f2e5324dd0cc"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da9f55e7afd616901fe2fe8a2aa369d474c0b2ad"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "5575c6983aca3c87532ca474079be1ba590eefa43477e8b2eda4e7ee4c34d3ff"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbd3134a8706b82a57eb4e5ae3740e41973a5c00"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "147bf32b69e7168a07f18b9ac6f8191433217aa70ed6ad00a051e4c4bdbd5ec1"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9364735ebcec80639ccf788eacf1faacba9c907e"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "b213060106b559fc5674380a5a6081c9defe89abdd698eaf598a13b78dcdb0cb"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libLLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9500ce17de575f609c17c4323b8de9f7415c04af"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "76d58eb759a5df3efb5fb4bf95906b4a4b082814c13aa54f356acbf8f98813c8"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "36b99e6807831fddd4847737c2016aec212b2940"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "8ea3e50648697a8091b632d4f7c63a92c61fadf9f4fe36cd7da290cc7702340a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2076ec90c117b74a61fc9a9f1db75e63455b295"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "0b8f1e4d55f3d706f014b8649b70ce2460154152fdd577db35c19fa9e0a1bb16"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d04285f5ed338232577a91b3de5e28802f0b001"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "f59b10f04afa35fac795a7b9147d6f0c4ed6091ecd7cb5028461f294eb421ba3"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49a3049643f8d65fde8e2bb7168cc6e6341fa1c3"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "6e5099ce927aeb03d9653384dc356f8d98b0aa17bd27c448510add0ff5e3f3ac"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35081c6ff656770fb3fd60feddeb6c478a1a4c6e"
os = "windows"

    [[libLLVM.download]]
    sha256 = "8a6eab93ab4ee6166217e7a6e4ff83d1239418cadd1e8a8a35781bf8505cc06a"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d0709ce881da411d4887ce70709492a53a692ba"
os = "windows"

    [[libLLVM.download]]
    sha256 = "15fe88d95d8c0690a65041845d5f955d407e288fd552f0937d6309e377adcc0d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "384c96d8d9ef61ba9156f788771b8bc99e9bcb41"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "332341f88e6284352f9d399b5670d41a4e09e6a60d3392b1e25e48057f945214"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b34788092be7edccd17da56bcdbf4fefd57bc25f"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "d4e0fdb4d958b069f3f32e2eaccae711afb2215f3ba1edf5b8fa2ad8c7a9ff23"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "be31d80750c3a8512515eeaf877ce8a647584b9d"
os = "macos"

    [[libLLVM.download]]
    sha256 = "f30470543c2067980edc3531d8b4986fbfca09acbd67d9096e31c8a100d10b22"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.x86_64-apple-darwin.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1475f4b850ac40ace74140e4a1373aa2a245e20a"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "243674afb0612a8fcb90c961a314406b08f56e5522b23788866a87345183daba"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71929bfd15d6ef239e9c50f6765b017d114afdd0"
libc = "glibc"
os = "linux"

    [[libLLVM.download]]
    sha256 = "b3ca59ec610d7cfa6876cb5205b993312273794874948905d07c0d00362b4ec5"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f489c0bb7b86747b5405f24ccdc7d7ddc38ee2eb"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "8eb5f2abb885dc7631fefa5d695c2bf8ca844c19c52815c00b6a12e739c93987"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65f2dcbd21964bd22fb52fd3910e6d8d7949d091"
libc = "musl"
os = "linux"

    [[libLLVM.download]]
    sha256 = "afe764a7e9f42dc93b11065843cd32a8f67756f83ebad7b6fbfb0937b3cd30a5"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[libLLVM]]
arch = "x86_64"
git-tree-sha1 = "b3db8ee7715fc6405da38a7eb4d3a181e7a20951"
os = "freebsd"

    [[libLLVM.download]]
    sha256 = "b27359e4c1d4f20945fafb40f83910d93ba64b2c6b89adccad67e5474ed0cba4"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ccc9f99adec1c07e28ae0e1c92ca1da3433c1786"
os = "windows"

    [[libLLVM.download]]
    sha256 = "c2d64d5eadeaf1cfb9720cd13ca59054157319fe7be4d6e1c62d31768f99994d"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32ce0f957a5f33778c5c20dcd77e57b65e0b5cb6"
os = "windows"

    [[libLLVM.download]]
    sha256 = "5586da31aeb15cb9a43d2270d2796b10a04c269e1cbcd7c3455148a40b355474"
    url = "https://github.com/JuliaBinaryWrappers/libLLVM_jll.jl/releases/download/libLLVM-v13.0.1+0/libLLVM.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
